spring:
  #  datasource:
  #    type: com.alibaba.druid.pool.DruidDataSource
  #    driver-class-name: oracle.jdbc.OracleDriver
  #    url: jdbc:oracle:thin:@//192.168.78.135:1521/MDB
  #    username: dbzs
  #    password: Ksecq1w2e3r4t5
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://10.140.101.135:1433;database=WSFKDB;Encrypt=False;
    username: sa
    password: q1w2e3r4t5...
  transaction:
    management:
      enabled: true
    default-timeout: 30s
    rollback-on-commit-failure: true
    assert-existing-transaction: true
    jta:
      enabled: true
mybatis:
  mapper-locations: classpath*:xml/*Mapper.xml
feature:
  scanOpc:
    enabled: true
  scheduledPostRequest:
    enabled: false
mqtt:
  enabled: false
  broker: tcp://192.168.40.20:1883
  clientId: mqttx_e4b1da48
  username: emqtest1
  password: passwd~!@eClient.10#$%^&*()_+
opcua:
  url: opc.tcp://10.140.101.134:49321
  username: ksec.opcua
  password: ksecq1w2e3r4t5...
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: INFO
ksecapi:
  url: http://127.0.0.1:80
