package com.example.repository.mapper;

import com.example.repository.model.EmsEquipmentclassproperty;
import com.example.repository.model.EmsEquipmentclasspropertyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EmsEquipmentclasspropertyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    long countByExample(EmsEquipmentclasspropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int deleteByExample(EmsEquipmentclasspropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int insert(EmsEquipmentclassproperty row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int insertSelective(EmsEquipmentclassproperty row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    List<EmsEquipmentclassproperty> selectByExample(EmsEquipmentclasspropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("row") EmsEquipmentclassproperty row, @Param("example") EmsEquipmentclasspropertyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int updateByExample(@Param("row") EmsEquipmentclassproperty row, @Param("example") EmsEquipmentclasspropertyExample example);
}