package com.example.repository.mapper;

import com.example.repository.model.EmsEquipmentelementclass;
import com.example.repository.model.EmsEquipmentelementclassExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EmsEquipmentelementclassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentelementclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    long countByExample(EmsEquipmentelementclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentelementclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int deleteByExample(EmsEquipmentelementclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentelementclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int insert(EmsEquipmentelementclass row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentelementclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int insertSelective(EmsEquipmentelementclass row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentelementclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    List<EmsEquipmentelementclass> selectByExample(EmsEquipmentelementclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentelementclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("row") EmsEquipmentelementclass row, @Param("example") EmsEquipmentelementclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentelementclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int updateByExample(@Param("row") EmsEquipmentelementclass row, @Param("example") EmsEquipmentelementclassExample example);
}