package com.example.repository.mapper;

import com.example.repository.model.EmsEquipmentelement;
import com.example.repository.model.EmsEquipmentelementExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EmsEquipmentelementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentelement
     *
     * @mbg.generated Wed Jan 11 23:20:17 GMT+08:00 2023
     */
    long countByExample(EmsEquipmentelementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentelement
     *
     * @mbg.generated Wed Jan 11 23:20:17 GMT+08:00 2023
     */
    int deleteByExample(EmsEquipmentelementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentelement
     *
     * @mbg.generated Wed Jan 11 23:20:17 GMT+08:00 2023
     */
    int insert(EmsEquipmentelement row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentelement
     *
     * @mbg.generated Wed Jan 11 23:20:17 GMT+08:00 2023
     */
    int insertSelective(EmsEquipmentelement row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentelement
     *
     * @mbg.generated Wed Jan 11 23:20:17 GMT+08:00 2023
     */
    List<EmsEquipmentelement> selectByExample(EmsEquipmentelementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentelement
     *
     * @mbg.generated Wed Jan 11 23:20:17 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("row") EmsEquipmentelement row, @Param("example") EmsEquipmentelementExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentelement
     *
     * @mbg.generated Wed Jan 11 23:20:17 GMT+08:00 2023
     */
    int updateByExample(@Param("row") EmsEquipmentelement row, @Param("example") EmsEquipmentelementExample example);
}