package com.example.repository.mapper;

import com.example.repository.model.EmsEquipmentclass;
import com.example.repository.model.EmsEquipmentclassExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EmsEquipmentclassMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    long countByExample(EmsEquipmentclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int deleteByExample(EmsEquipmentclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int deleteByPrimaryKey(String equipmentclassid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int insert(EmsEquipmentclass row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int insertSelective(EmsEquipmentclass row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    List<EmsEquipmentclass> selectByExample(EmsEquipmentclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    EmsEquipmentclass selectByPrimaryKey(String equipmentclassid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("row") EmsEquipmentclass row, @Param("example") EmsEquipmentclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int updateByExample(@Param("row") EmsEquipmentclass row, @Param("example") EmsEquipmentclassExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int updateByPrimaryKeySelective(EmsEquipmentclass row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    int updateByPrimaryKey(EmsEquipmentclass row);
}