package com.example.repository.mapper;

import com.example.repository.model.EmsPreheatRunTime;
import com.example.repository.model.EmsPreheatRunTimeExample;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;

public interface EmsPreheatRunTimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMS_PREHEAT_RUN_TIME
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    long countByExample(EmsPreheatRunTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMS_PREHEAT_RUN_TIME
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    int deleteByExample(EmsPreheatRunTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMS_PREHEAT_RUN_TIME
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    int deleteByPrimaryKey(Date date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMS_PREHEAT_RUN_TIME
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    int insert(EmsPreheatRunTime row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMS_PREHEAT_RUN_TIME
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    int insertSelective(EmsPreheatRunTime row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMS_PREHEAT_RUN_TIME
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    List<EmsPreheatRunTime> selectByExample(EmsPreheatRunTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMS_PREHEAT_RUN_TIME
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    EmsPreheatRunTime selectByPrimaryKey(Date date);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMS_PREHEAT_RUN_TIME
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    int updateByExampleSelective(@Param("row") EmsPreheatRunTime row, @Param("example") EmsPreheatRunTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMS_PREHEAT_RUN_TIME
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    int updateByExample(@Param("row") EmsPreheatRunTime row, @Param("example") EmsPreheatRunTimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMS_PREHEAT_RUN_TIME
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    int updateByPrimaryKeySelective(EmsPreheatRunTime row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EMS_PREHEAT_RUN_TIME
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    int updateByPrimaryKey(EmsPreheatRunTime row);
}