package com.example.repository.mapper;

import com.example.repository.model.PdsMqtttopicTrigger;
import com.example.repository.model.PdsMqtttopicTriggerExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PdsMqtttopicTriggerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDS_MQTTTOPIC_TRIGGER
     *
     * @mbg.generated Tue May 30 18:15:56 GMT+08:00 2023
     */
    long countByExample(PdsMqtttopicTriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDS_MQTTTOPIC_TRIGGER
     *
     * @mbg.generated Tue May 30 18:15:56 GMT+08:00 2023
     */
    int deleteByExample(PdsMqtttopicTriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDS_MQTTTOPIC_TRIGGER
     *
     * @mbg.generated Tue May 30 18:15:56 GMT+08:00 2023
     */
    int deleteByPrimaryKey(Long triggerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDS_MQTTTOPIC_TRIGGER
     *
     * @mbg.generated Tue May 30 18:15:56 GMT+08:00 2023
     */
    int insert(PdsMqtttopicTrigger row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDS_MQTTTOPIC_TRIGGER
     *
     * @mbg.generated Tue May 30 18:15:56 GMT+08:00 2023
     */
    int insertSelective(PdsMqtttopicTrigger row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDS_MQTTTOPIC_TRIGGER
     *
     * @mbg.generated Tue May 30 18:15:56 GMT+08:00 2023
     */
    List<PdsMqtttopicTrigger> selectByExample(PdsMqtttopicTriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDS_MQTTTOPIC_TRIGGER
     *
     * @mbg.generated Tue May 30 18:15:56 GMT+08:00 2023
     */
    PdsMqtttopicTrigger selectByPrimaryKey(Long triggerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDS_MQTTTOPIC_TRIGGER
     *
     * @mbg.generated Tue May 30 18:15:56 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("row") PdsMqtttopicTrigger row, @Param("example") PdsMqtttopicTriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDS_MQTTTOPIC_TRIGGER
     *
     * @mbg.generated Tue May 30 18:15:56 GMT+08:00 2023
     */
    int updateByExample(@Param("row") PdsMqtttopicTrigger row, @Param("example") PdsMqtttopicTriggerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDS_MQTTTOPIC_TRIGGER
     *
     * @mbg.generated Tue May 30 18:15:56 GMT+08:00 2023
     */
    int updateByPrimaryKeySelective(PdsMqtttopicTrigger row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PDS_MQTTTOPIC_TRIGGER
     *
     * @mbg.generated Tue May 30 18:15:56 GMT+08:00 2023
     */
    int updateByPrimaryKey(PdsMqtttopicTrigger row);
}