package com.example.repository.mapper;

import com.example.repository.model.PrdCelltaskstoprecord;
import com.example.repository.model.PrdCelltaskstoprecordExample;
import com.example.repository.model.PrdCelltaskstoprecordKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PrdCelltaskstoprecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    long countByExample(PrdCelltaskstoprecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    int deleteByExample(PrdCelltaskstoprecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    int deleteByPrimaryKey(PrdCelltaskstoprecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    int insert(PrdCelltaskstoprecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    int insertSelective(PrdCelltaskstoprecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    List<PrdCelltaskstoprecord> selectByExample(PrdCelltaskstoprecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    PrdCelltaskstoprecord selectByPrimaryKey(PrdCelltaskstoprecordKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    int updateByExampleSelective(@Param("row") PrdCelltaskstoprecord row, @Param("example") PrdCelltaskstoprecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    int updateByExample(@Param("row") PrdCelltaskstoprecord row, @Param("example") PrdCelltaskstoprecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    int updateByPrimaryKeySelective(PrdCelltaskstoprecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    int updateByPrimaryKey(PrdCelltaskstoprecord row);
}