package com.example.repository.mapper;

import com.example.repository.model.PrdUnitcmd;
import com.example.repository.model.PrdUnitcmdExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PrdUnitcmdMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    long countByExample(PrdUnitcmdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    int deleteByExample(PrdUnitcmdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    int deleteByPrimaryKey(String cmdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    int insert(PrdUnitcmd row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    int insertSelective(PrdUnitcmd row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    List<PrdUnitcmd> selectByExample(PrdUnitcmdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    PrdUnitcmd selectByPrimaryKey(String cmdid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("row") PrdUnitcmd row, @Param("example") PrdUnitcmdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    int updateByExample(@Param("row") PrdUnitcmd row, @Param("example") PrdUnitcmdExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    int updateByPrimaryKeySelective(PrdUnitcmd row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    int updateByPrimaryKey(PrdUnitcmd row);
}