package com.example.repository.mapper;

import com.example.repository.model.PrdUnitcmdParas;
import com.example.repository.model.PrdUnitcmdParasExample;
import com.example.repository.model.PrdUnitcmdParasKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PrdUnitcmdParasMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD_PARAS
     *
     * @mbg.generated Tue Dec 19 10:57:55 GMT+08:00 2023
     */
    long countByExample(PrdUnitcmdParasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD_PARAS
     *
     * @mbg.generated Tue Dec 19 10:57:55 GMT+08:00 2023
     */
    int deleteByExample(PrdUnitcmdParasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD_PARAS
     *
     * @mbg.generated Tue Dec 19 10:57:55 GMT+08:00 2023
     */
    int deleteByPrimaryKey(PrdUnitcmdParasKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD_PARAS
     *
     * @mbg.generated Tue Dec 19 10:57:55 GMT+08:00 2023
     */
    int insert(PrdUnitcmdParas row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD_PARAS
     *
     * @mbg.generated Tue Dec 19 10:57:55 GMT+08:00 2023
     */
    int insertSelective(PrdUnitcmdParas row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD_PARAS
     *
     * @mbg.generated Tue Dec 19 10:57:55 GMT+08:00 2023
     */
    List<PrdUnitcmdParas> selectByExample(PrdUnitcmdParasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD_PARAS
     *
     * @mbg.generated Tue Dec 19 10:57:55 GMT+08:00 2023
     */
    PrdUnitcmdParas selectByPrimaryKey(PrdUnitcmdParasKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD_PARAS
     *
     * @mbg.generated Tue Dec 19 10:57:55 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("row") PrdUnitcmdParas row, @Param("example") PrdUnitcmdParasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD_PARAS
     *
     * @mbg.generated Tue Dec 19 10:57:55 GMT+08:00 2023
     */
    int updateByExample(@Param("row") PrdUnitcmdParas row, @Param("example") PrdUnitcmdParasExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD_PARAS
     *
     * @mbg.generated Tue Dec 19 10:57:55 GMT+08:00 2023
     */
    int updateByPrimaryKeySelective(PrdUnitcmdParas row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRD_UNITCMD_PARAS
     *
     * @mbg.generated Tue Dec 19 10:57:55 GMT+08:00 2023
     */
    int updateByPrimaryKey(PrdUnitcmdParas row);
}