package com.example.repository.mapper;

import com.example.repository.model.Siloinfo;
import com.example.repository.model.SiloinfoExample;
import com.example.repository.model.SiloinfoKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SiloinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    long countByExample(SiloinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    int deleteByExample(SiloinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    int deleteByPrimaryKey(SiloinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    int insert(Siloinfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    int insertSelective(Siloinfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    List<Siloinfo> selectByExample(SiloinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    Siloinfo selectByPrimaryKey(SiloinfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    int updateByExampleSelective(@Param("row") Siloinfo row, @Param("example") SiloinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    int updateByExample(@Param("row") Siloinfo row, @Param("example") SiloinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    int updateByPrimaryKeySelective(Siloinfo row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    int updateByPrimaryKey(Siloinfo row);
}