package com.example.repository.mapper;

import com.example.repository.model.VPrdCelltaskstoprecord;
import com.example.repository.model.VPrdCelltaskstoprecordExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface VPrdCelltaskstoprecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Thu Jan 18 10:08:01 GMT+08:00 2024
     */
    long countByExample(VPrdCelltaskstoprecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Thu Jan 18 10:08:01 GMT+08:00 2024
     */
    int deleteByExample(VPrdCelltaskstoprecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Thu Jan 18 10:08:01 GMT+08:00 2024
     */
    int insert(VPrdCelltaskstoprecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Thu Jan 18 10:08:01 GMT+08:00 2024
     */
    int insertSelective(VPrdCelltaskstoprecord row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Thu Jan 18 10:08:01 GMT+08:00 2024
     */
    List<VPrdCelltaskstoprecord> selectByExample(VPrdCelltaskstoprecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Thu Jan 18 10:08:01 GMT+08:00 2024
     */
    int updateByExampleSelective(@Param("row") VPrdCelltaskstoprecord row, @Param("example") VPrdCelltaskstoprecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table V_PRD_CELLTASKSTOPRECORD
     *
     * @mbg.generated Thu Jan 18 10:08:01 GMT+08:00 2024
     */
    int updateByExample(@Param("row") VPrdCelltaskstoprecord row, @Param("example") VPrdCelltaskstoprecordExample example);
}