package com.example.repository.model;

public class AppConfigItemsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CONFIG_ITEMS.PARENTCFG
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    private String parentcfg;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column APP_CONFIG_ITEMS.PROPERTYID
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    private String propertyid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CONFIG_ITEMS.PARENTCFG
     *
     * @return the value of APP_CONFIG_ITEMS.PARENTCFG
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public String getParentcfg() {
        return parentcfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CONFIG_ITEMS.PARENTCFG
     *
     * @param parentcfg the value for APP_CONFIG_ITEMS.PARENTCFG
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public void setParentcfg(String parentcfg) {
        this.parentcfg = parentcfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column APP_CONFIG_ITEMS.PROPERTYID
     *
     * @return the value of APP_CONFIG_ITEMS.PROPERTYID
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public String getPropertyid() {
        return propertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column APP_CONFIG_ITEMS.PROPERTYID
     *
     * @param propertyid the value for APP_CONFIG_ITEMS.PROPERTYID
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public void setPropertyid(String propertyid) {
        this.propertyid = propertyid;
    }
}