package com.example.repository.model;

import java.util.ArrayList;
import java.util.List;

public class AppConfigItemsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public AppConfigItemsExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andParentcfgIsNull() {
            addCriterion("PARENTCFG is null");
            return (Criteria) this;
        }

        public Criteria andParentcfgIsNotNull() {
            addCriterion("PARENTCFG is not null");
            return (Criteria) this;
        }

        public Criteria andParentcfgEqualTo(String value) {
            addCriterion("PARENTCFG =", value, "parentcfg");
            return (Criteria) this;
        }

        public Criteria andParentcfgNotEqualTo(String value) {
            addCriterion("PARENTCFG <>", value, "parentcfg");
            return (Criteria) this;
        }

        public Criteria andParentcfgGreaterThan(String value) {
            addCriterion("PARENTCFG >", value, "parentcfg");
            return (Criteria) this;
        }

        public Criteria andParentcfgGreaterThanOrEqualTo(String value) {
            addCriterion("PARENTCFG >=", value, "parentcfg");
            return (Criteria) this;
        }

        public Criteria andParentcfgLessThan(String value) {
            addCriterion("PARENTCFG <", value, "parentcfg");
            return (Criteria) this;
        }

        public Criteria andParentcfgLessThanOrEqualTo(String value) {
            addCriterion("PARENTCFG <=", value, "parentcfg");
            return (Criteria) this;
        }

        public Criteria andParentcfgLike(String value) {
            addCriterion("PARENTCFG like", value, "parentcfg");
            return (Criteria) this;
        }

        public Criteria andParentcfgNotLike(String value) {
            addCriterion("PARENTCFG not like", value, "parentcfg");
            return (Criteria) this;
        }

        public Criteria andParentcfgIn(List<String> values) {
            addCriterion("PARENTCFG in", values, "parentcfg");
            return (Criteria) this;
        }

        public Criteria andParentcfgNotIn(List<String> values) {
            addCriterion("PARENTCFG not in", values, "parentcfg");
            return (Criteria) this;
        }

        public Criteria andParentcfgBetween(String value1, String value2) {
            addCriterion("PARENTCFG between", value1, value2, "parentcfg");
            return (Criteria) this;
        }

        public Criteria andParentcfgNotBetween(String value1, String value2) {
            addCriterion("PARENTCFG not between", value1, value2, "parentcfg");
            return (Criteria) this;
        }

        public Criteria andPropertyidIsNull() {
            addCriterion("PROPERTYID is null");
            return (Criteria) this;
        }

        public Criteria andPropertyidIsNotNull() {
            addCriterion("PROPERTYID is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyidEqualTo(String value) {
            addCriterion("PROPERTYID =", value, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidNotEqualTo(String value) {
            addCriterion("PROPERTYID <>", value, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidGreaterThan(String value) {
            addCriterion("PROPERTYID >", value, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidGreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTYID >=", value, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidLessThan(String value) {
            addCriterion("PROPERTYID <", value, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidLessThanOrEqualTo(String value) {
            addCriterion("PROPERTYID <=", value, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidLike(String value) {
            addCriterion("PROPERTYID like", value, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidNotLike(String value) {
            addCriterion("PROPERTYID not like", value, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidIn(List<String> values) {
            addCriterion("PROPERTYID in", values, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidNotIn(List<String> values) {
            addCriterion("PROPERTYID not in", values, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidBetween(String value1, String value2) {
            addCriterion("PROPERTYID between", value1, value2, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidNotBetween(String value1, String value2) {
            addCriterion("PROPERTYID not between", value1, value2, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertynameIsNull() {
            addCriterion("PROPERTYNAME is null");
            return (Criteria) this;
        }

        public Criteria andPropertynameIsNotNull() {
            addCriterion("PROPERTYNAME is not null");
            return (Criteria) this;
        }

        public Criteria andPropertynameEqualTo(String value) {
            addCriterion("PROPERTYNAME =", value, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameNotEqualTo(String value) {
            addCriterion("PROPERTYNAME <>", value, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameGreaterThan(String value) {
            addCriterion("PROPERTYNAME >", value, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameGreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTYNAME >=", value, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameLessThan(String value) {
            addCriterion("PROPERTYNAME <", value, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameLessThanOrEqualTo(String value) {
            addCriterion("PROPERTYNAME <=", value, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameLike(String value) {
            addCriterion("PROPERTYNAME like", value, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameNotLike(String value) {
            addCriterion("PROPERTYNAME not like", value, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameIn(List<String> values) {
            addCriterion("PROPERTYNAME in", values, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameNotIn(List<String> values) {
            addCriterion("PROPERTYNAME not in", values, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameBetween(String value1, String value2) {
            addCriterion("PROPERTYNAME between", value1, value2, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameNotBetween(String value1, String value2) {
            addCriterion("PROPERTYNAME not between", value1, value2, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueIsNull() {
            addCriterion("PROPERTYVALUE is null");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueIsNotNull() {
            addCriterion("PROPERTYVALUE is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueEqualTo(String value) {
            addCriterion("PROPERTYVALUE =", value, "propertyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueNotEqualTo(String value) {
            addCriterion("PROPERTYVALUE <>", value, "propertyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueGreaterThan(String value) {
            addCriterion("PROPERTYVALUE >", value, "propertyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueGreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTYVALUE >=", value, "propertyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueLessThan(String value) {
            addCriterion("PROPERTYVALUE <", value, "propertyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueLessThanOrEqualTo(String value) {
            addCriterion("PROPERTYVALUE <=", value, "propertyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueLike(String value) {
            addCriterion("PROPERTYVALUE like", value, "propertyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueNotLike(String value) {
            addCriterion("PROPERTYVALUE not like", value, "propertyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueIn(List<String> values) {
            addCriterion("PROPERTYVALUE in", values, "propertyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueNotIn(List<String> values) {
            addCriterion("PROPERTYVALUE not in", values, "propertyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueBetween(String value1, String value2) {
            addCriterion("PROPERTYVALUE between", value1, value2, "propertyvalue");
            return (Criteria) this;
        }

        public Criteria andPropertyvalueNotBetween(String value1, String value2) {
            addCriterion("PROPERTYVALUE not between", value1, value2, "propertyvalue");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue1IsNull() {
            addCriterion("PROPERTYVALUE1 is null");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue1IsNotNull() {
            addCriterion("PROPERTYVALUE1 is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue1EqualTo(String value) {
            addCriterion("PROPERTYVALUE1 =", value, "propertyvalue1");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue1NotEqualTo(String value) {
            addCriterion("PROPERTYVALUE1 <>", value, "propertyvalue1");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue1GreaterThan(String value) {
            addCriterion("PROPERTYVALUE1 >", value, "propertyvalue1");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue1GreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTYVALUE1 >=", value, "propertyvalue1");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue1LessThan(String value) {
            addCriterion("PROPERTYVALUE1 <", value, "propertyvalue1");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue1LessThanOrEqualTo(String value) {
            addCriterion("PROPERTYVALUE1 <=", value, "propertyvalue1");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue1Like(String value) {
            addCriterion("PROPERTYVALUE1 like", value, "propertyvalue1");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue1NotLike(String value) {
            addCriterion("PROPERTYVALUE1 not like", value, "propertyvalue1");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue1In(List<String> values) {
            addCriterion("PROPERTYVALUE1 in", values, "propertyvalue1");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue1NotIn(List<String> values) {
            addCriterion("PROPERTYVALUE1 not in", values, "propertyvalue1");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue1Between(String value1, String value2) {
            addCriterion("PROPERTYVALUE1 between", value1, value2, "propertyvalue1");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue1NotBetween(String value1, String value2) {
            addCriterion("PROPERTYVALUE1 not between", value1, value2, "propertyvalue1");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue2IsNull() {
            addCriterion("PROPERTYVALUE2 is null");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue2IsNotNull() {
            addCriterion("PROPERTYVALUE2 is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue2EqualTo(String value) {
            addCriterion("PROPERTYVALUE2 =", value, "propertyvalue2");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue2NotEqualTo(String value) {
            addCriterion("PROPERTYVALUE2 <>", value, "propertyvalue2");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue2GreaterThan(String value) {
            addCriterion("PROPERTYVALUE2 >", value, "propertyvalue2");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue2GreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTYVALUE2 >=", value, "propertyvalue2");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue2LessThan(String value) {
            addCriterion("PROPERTYVALUE2 <", value, "propertyvalue2");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue2LessThanOrEqualTo(String value) {
            addCriterion("PROPERTYVALUE2 <=", value, "propertyvalue2");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue2Like(String value) {
            addCriterion("PROPERTYVALUE2 like", value, "propertyvalue2");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue2NotLike(String value) {
            addCriterion("PROPERTYVALUE2 not like", value, "propertyvalue2");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue2In(List<String> values) {
            addCriterion("PROPERTYVALUE2 in", values, "propertyvalue2");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue2NotIn(List<String> values) {
            addCriterion("PROPERTYVALUE2 not in", values, "propertyvalue2");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue2Between(String value1, String value2) {
            addCriterion("PROPERTYVALUE2 between", value1, value2, "propertyvalue2");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue2NotBetween(String value1, String value2) {
            addCriterion("PROPERTYVALUE2 not between", value1, value2, "propertyvalue2");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue3IsNull() {
            addCriterion("PROPERTYVALUE3 is null");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue3IsNotNull() {
            addCriterion("PROPERTYVALUE3 is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue3EqualTo(String value) {
            addCriterion("PROPERTYVALUE3 =", value, "propertyvalue3");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue3NotEqualTo(String value) {
            addCriterion("PROPERTYVALUE3 <>", value, "propertyvalue3");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue3GreaterThan(String value) {
            addCriterion("PROPERTYVALUE3 >", value, "propertyvalue3");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue3GreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTYVALUE3 >=", value, "propertyvalue3");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue3LessThan(String value) {
            addCriterion("PROPERTYVALUE3 <", value, "propertyvalue3");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue3LessThanOrEqualTo(String value) {
            addCriterion("PROPERTYVALUE3 <=", value, "propertyvalue3");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue3Like(String value) {
            addCriterion("PROPERTYVALUE3 like", value, "propertyvalue3");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue3NotLike(String value) {
            addCriterion("PROPERTYVALUE3 not like", value, "propertyvalue3");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue3In(List<String> values) {
            addCriterion("PROPERTYVALUE3 in", values, "propertyvalue3");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue3NotIn(List<String> values) {
            addCriterion("PROPERTYVALUE3 not in", values, "propertyvalue3");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue3Between(String value1, String value2) {
            addCriterion("PROPERTYVALUE3 between", value1, value2, "propertyvalue3");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue3NotBetween(String value1, String value2) {
            addCriterion("PROPERTYVALUE3 not between", value1, value2, "propertyvalue3");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue4IsNull() {
            addCriterion("PROPERTYVALUE4 is null");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue4IsNotNull() {
            addCriterion("PROPERTYVALUE4 is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue4EqualTo(String value) {
            addCriterion("PROPERTYVALUE4 =", value, "propertyvalue4");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue4NotEqualTo(String value) {
            addCriterion("PROPERTYVALUE4 <>", value, "propertyvalue4");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue4GreaterThan(String value) {
            addCriterion("PROPERTYVALUE4 >", value, "propertyvalue4");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue4GreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTYVALUE4 >=", value, "propertyvalue4");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue4LessThan(String value) {
            addCriterion("PROPERTYVALUE4 <", value, "propertyvalue4");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue4LessThanOrEqualTo(String value) {
            addCriterion("PROPERTYVALUE4 <=", value, "propertyvalue4");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue4Like(String value) {
            addCriterion("PROPERTYVALUE4 like", value, "propertyvalue4");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue4NotLike(String value) {
            addCriterion("PROPERTYVALUE4 not like", value, "propertyvalue4");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue4In(List<String> values) {
            addCriterion("PROPERTYVALUE4 in", values, "propertyvalue4");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue4NotIn(List<String> values) {
            addCriterion("PROPERTYVALUE4 not in", values, "propertyvalue4");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue4Between(String value1, String value2) {
            addCriterion("PROPERTYVALUE4 between", value1, value2, "propertyvalue4");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue4NotBetween(String value1, String value2) {
            addCriterion("PROPERTYVALUE4 not between", value1, value2, "propertyvalue4");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue5IsNull() {
            addCriterion("PROPERTYVALUE5 is null");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue5IsNotNull() {
            addCriterion("PROPERTYVALUE5 is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue5EqualTo(String value) {
            addCriterion("PROPERTYVALUE5 =", value, "propertyvalue5");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue5NotEqualTo(String value) {
            addCriterion("PROPERTYVALUE5 <>", value, "propertyvalue5");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue5GreaterThan(String value) {
            addCriterion("PROPERTYVALUE5 >", value, "propertyvalue5");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue5GreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTYVALUE5 >=", value, "propertyvalue5");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue5LessThan(String value) {
            addCriterion("PROPERTYVALUE5 <", value, "propertyvalue5");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue5LessThanOrEqualTo(String value) {
            addCriterion("PROPERTYVALUE5 <=", value, "propertyvalue5");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue5Like(String value) {
            addCriterion("PROPERTYVALUE5 like", value, "propertyvalue5");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue5NotLike(String value) {
            addCriterion("PROPERTYVALUE5 not like", value, "propertyvalue5");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue5In(List<String> values) {
            addCriterion("PROPERTYVALUE5 in", values, "propertyvalue5");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue5NotIn(List<String> values) {
            addCriterion("PROPERTYVALUE5 not in", values, "propertyvalue5");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue5Between(String value1, String value2) {
            addCriterion("PROPERTYVALUE5 between", value1, value2, "propertyvalue5");
            return (Criteria) this;
        }

        public Criteria andPropertyvalue5NotBetween(String value1, String value2) {
            addCriterion("PROPERTYVALUE5 not between", value1, value2, "propertyvalue5");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated do_not_delete_during_merge Fri May 16 11:19:14 CST 2025
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table APP_CONFIG_ITEMS
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}