package com.example.repository.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EmsEquipmentclassExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public EmsEquipmentclassExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andEquipmentclassidIsNull() {
            addCriterion("EQUIPMENTCLASSID is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidIsNotNull() {
            addCriterion("EQUIPMENTCLASSID is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidEqualTo(String value) {
            addCriterion("EQUIPMENTCLASSID =", value, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidNotEqualTo(String value) {
            addCriterion("EQUIPMENTCLASSID <>", value, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidGreaterThan(String value) {
            addCriterion("EQUIPMENTCLASSID >", value, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIPMENTCLASSID >=", value, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidLessThan(String value) {
            addCriterion("EQUIPMENTCLASSID <", value, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidLessThanOrEqualTo(String value) {
            addCriterion("EQUIPMENTCLASSID <=", value, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidLike(String value) {
            addCriterion("EQUIPMENTCLASSID like", value, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidNotLike(String value) {
            addCriterion("EQUIPMENTCLASSID not like", value, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidIn(List<String> values) {
            addCriterion("EQUIPMENTCLASSID in", values, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidNotIn(List<String> values) {
            addCriterion("EQUIPMENTCLASSID not in", values, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidBetween(String value1, String value2) {
            addCriterion("EQUIPMENTCLASSID between", value1, value2, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidNotBetween(String value1, String value2) {
            addCriterion("EQUIPMENTCLASSID not between", value1, value2, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassnameIsNull() {
            addCriterion("EQUIPMENTCLASSNAME is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassnameIsNotNull() {
            addCriterion("EQUIPMENTCLASSNAME is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassnameEqualTo(String value) {
            addCriterion("EQUIPMENTCLASSNAME =", value, "equipmentclassname");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassnameNotEqualTo(String value) {
            addCriterion("EQUIPMENTCLASSNAME <>", value, "equipmentclassname");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassnameGreaterThan(String value) {
            addCriterion("EQUIPMENTCLASSNAME >", value, "equipmentclassname");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassnameGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIPMENTCLASSNAME >=", value, "equipmentclassname");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassnameLessThan(String value) {
            addCriterion("EQUIPMENTCLASSNAME <", value, "equipmentclassname");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassnameLessThanOrEqualTo(String value) {
            addCriterion("EQUIPMENTCLASSNAME <=", value, "equipmentclassname");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassnameLike(String value) {
            addCriterion("EQUIPMENTCLASSNAME like", value, "equipmentclassname");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassnameNotLike(String value) {
            addCriterion("EQUIPMENTCLASSNAME not like", value, "equipmentclassname");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassnameIn(List<String> values) {
            addCriterion("EQUIPMENTCLASSNAME in", values, "equipmentclassname");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassnameNotIn(List<String> values) {
            addCriterion("EQUIPMENTCLASSNAME not in", values, "equipmentclassname");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassnameBetween(String value1, String value2) {
            addCriterion("EQUIPMENTCLASSNAME between", value1, value2, "equipmentclassname");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassnameNotBetween(String value1, String value2) {
            addCriterion("EQUIPMENTCLASSNAME not between", value1, value2, "equipmentclassname");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("AUTHOR is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("AUTHOR is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(String value) {
            addCriterion("AUTHOR =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(String value) {
            addCriterion("AUTHOR <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(String value) {
            addCriterion("AUTHOR >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("AUTHOR >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(String value) {
            addCriterion("AUTHOR <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(String value) {
            addCriterion("AUTHOR <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLike(String value) {
            addCriterion("AUTHOR like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotLike(String value) {
            addCriterion("AUTHOR not like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<String> values) {
            addCriterion("AUTHOR in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<String> values) {
            addCriterion("AUTHOR not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(String value1, String value2) {
            addCriterion("AUTHOR between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(String value1, String value2) {
            addCriterion("AUTHOR not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andApprovedbyIsNull() {
            addCriterion("APPROVEDBY is null");
            return (Criteria) this;
        }

        public Criteria andApprovedbyIsNotNull() {
            addCriterion("APPROVEDBY is not null");
            return (Criteria) this;
        }

        public Criteria andApprovedbyEqualTo(String value) {
            addCriterion("APPROVEDBY =", value, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyNotEqualTo(String value) {
            addCriterion("APPROVEDBY <>", value, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyGreaterThan(String value) {
            addCriterion("APPROVEDBY >", value, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyGreaterThanOrEqualTo(String value) {
            addCriterion("APPROVEDBY >=", value, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyLessThan(String value) {
            addCriterion("APPROVEDBY <", value, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyLessThanOrEqualTo(String value) {
            addCriterion("APPROVEDBY <=", value, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyLike(String value) {
            addCriterion("APPROVEDBY like", value, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyNotLike(String value) {
            addCriterion("APPROVEDBY not like", value, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyIn(List<String> values) {
            addCriterion("APPROVEDBY in", values, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyNotIn(List<String> values) {
            addCriterion("APPROVEDBY not in", values, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyBetween(String value1, String value2) {
            addCriterion("APPROVEDBY between", value1, value2, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyNotBetween(String value1, String value2) {
            addCriterion("APPROVEDBY not between", value1, value2, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovaldateIsNull() {
            addCriterion("APPROVALDATE is null");
            return (Criteria) this;
        }

        public Criteria andApprovaldateIsNotNull() {
            addCriterion("APPROVALDATE is not null");
            return (Criteria) this;
        }

        public Criteria andApprovaldateEqualTo(Date value) {
            addCriterion("APPROVALDATE =", value, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateNotEqualTo(Date value) {
            addCriterion("APPROVALDATE <>", value, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateGreaterThan(Date value) {
            addCriterion("APPROVALDATE >", value, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateGreaterThanOrEqualTo(Date value) {
            addCriterion("APPROVALDATE >=", value, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateLessThan(Date value) {
            addCriterion("APPROVALDATE <", value, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateLessThanOrEqualTo(Date value) {
            addCriterion("APPROVALDATE <=", value, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateIn(List<Date> values) {
            addCriterion("APPROVALDATE in", values, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateNotIn(List<Date> values) {
            addCriterion("APPROVALDATE not in", values, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateBetween(Date value1, Date value2) {
            addCriterion("APPROVALDATE between", value1, value2, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateNotBetween(Date value1, Date value2) {
            addCriterion("APPROVALDATE not between", value1, value2, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andEquipmentclasscodeIsNull() {
            addCriterion("EQUIPMENTCLASSCODE is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentclasscodeIsNotNull() {
            addCriterion("EQUIPMENTCLASSCODE is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentclasscodeEqualTo(String value) {
            addCriterion("EQUIPMENTCLASSCODE =", value, "equipmentclasscode");
            return (Criteria) this;
        }

        public Criteria andEquipmentclasscodeNotEqualTo(String value) {
            addCriterion("EQUIPMENTCLASSCODE <>", value, "equipmentclasscode");
            return (Criteria) this;
        }

        public Criteria andEquipmentclasscodeGreaterThan(String value) {
            addCriterion("EQUIPMENTCLASSCODE >", value, "equipmentclasscode");
            return (Criteria) this;
        }

        public Criteria andEquipmentclasscodeGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIPMENTCLASSCODE >=", value, "equipmentclasscode");
            return (Criteria) this;
        }

        public Criteria andEquipmentclasscodeLessThan(String value) {
            addCriterion("EQUIPMENTCLASSCODE <", value, "equipmentclasscode");
            return (Criteria) this;
        }

        public Criteria andEquipmentclasscodeLessThanOrEqualTo(String value) {
            addCriterion("EQUIPMENTCLASSCODE <=", value, "equipmentclasscode");
            return (Criteria) this;
        }

        public Criteria andEquipmentclasscodeLike(String value) {
            addCriterion("EQUIPMENTCLASSCODE like", value, "equipmentclasscode");
            return (Criteria) this;
        }

        public Criteria andEquipmentclasscodeNotLike(String value) {
            addCriterion("EQUIPMENTCLASSCODE not like", value, "equipmentclasscode");
            return (Criteria) this;
        }

        public Criteria andEquipmentclasscodeIn(List<String> values) {
            addCriterion("EQUIPMENTCLASSCODE in", values, "equipmentclasscode");
            return (Criteria) this;
        }

        public Criteria andEquipmentclasscodeNotIn(List<String> values) {
            addCriterion("EQUIPMENTCLASSCODE not in", values, "equipmentclasscode");
            return (Criteria) this;
        }

        public Criteria andEquipmentclasscodeBetween(String value1, String value2) {
            addCriterion("EQUIPMENTCLASSCODE between", value1, value2, "equipmentclasscode");
            return (Criteria) this;
        }

        public Criteria andEquipmentclasscodeNotBetween(String value1, String value2) {
            addCriterion("EQUIPMENTCLASSCODE not between", value1, value2, "equipmentclasscode");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated do_not_delete_during_merge Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ems_equipmentclass
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}