package com.example.repository.model;

import java.util.Date;

public class EmsEquipmentclass {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclass.EQUIPMENTCLASSID
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String equipmentclassid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclass.EQUIPMENTCLASSNAME
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String equipmentclassname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclass.DESCRIPTION
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclass.AUTHOR
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclass.CREATEDATE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclass.APPROVEDBY
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String approvedby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclass.APPROVALDATE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private Date approvaldate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclass.EQUIPMENTCLASSCODE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String equipmentclasscode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclass.EQUIPMENTCLASSID
     *
     * @return the value of ems_equipmentclass.EQUIPMENTCLASSID
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getEquipmentclassid() {
        return equipmentclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclass.EQUIPMENTCLASSID
     *
     * @param equipmentclassid the value for ems_equipmentclass.EQUIPMENTCLASSID
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setEquipmentclassid(String equipmentclassid) {
        this.equipmentclassid = equipmentclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclass.EQUIPMENTCLASSNAME
     *
     * @return the value of ems_equipmentclass.EQUIPMENTCLASSNAME
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getEquipmentclassname() {
        return equipmentclassname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclass.EQUIPMENTCLASSNAME
     *
     * @param equipmentclassname the value for ems_equipmentclass.EQUIPMENTCLASSNAME
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setEquipmentclassname(String equipmentclassname) {
        this.equipmentclassname = equipmentclassname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclass.DESCRIPTION
     *
     * @return the value of ems_equipmentclass.DESCRIPTION
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclass.DESCRIPTION
     *
     * @param description the value for ems_equipmentclass.DESCRIPTION
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclass.AUTHOR
     *
     * @return the value of ems_equipmentclass.AUTHOR
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclass.AUTHOR
     *
     * @param author the value for ems_equipmentclass.AUTHOR
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclass.CREATEDATE
     *
     * @return the value of ems_equipmentclass.CREATEDATE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclass.CREATEDATE
     *
     * @param createdate the value for ems_equipmentclass.CREATEDATE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclass.APPROVEDBY
     *
     * @return the value of ems_equipmentclass.APPROVEDBY
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getApprovedby() {
        return approvedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclass.APPROVEDBY
     *
     * @param approvedby the value for ems_equipmentclass.APPROVEDBY
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setApprovedby(String approvedby) {
        this.approvedby = approvedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclass.APPROVALDATE
     *
     * @return the value of ems_equipmentclass.APPROVALDATE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public Date getApprovaldate() {
        return approvaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclass.APPROVALDATE
     *
     * @param approvaldate the value for ems_equipmentclass.APPROVALDATE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setApprovaldate(Date approvaldate) {
        this.approvaldate = approvaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclass.EQUIPMENTCLASSCODE
     *
     * @return the value of ems_equipmentclass.EQUIPMENTCLASSCODE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getEquipmentclasscode() {
        return equipmentclasscode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclass.EQUIPMENTCLASSCODE
     *
     * @param equipmentclasscode the value for ems_equipmentclass.EQUIPMENTCLASSCODE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setEquipmentclasscode(String equipmentclasscode) {
        this.equipmentclasscode = equipmentclasscode;
    }
}