package com.example.repository.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EmsEquipmentclasspropertyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    public EmsEquipmentclasspropertyExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPropertyidIsNull() {
            addCriterion("PROPERTYID is null");
            return (Criteria) this;
        }

        public Criteria andPropertyidIsNotNull() {
            addCriterion("PROPERTYID is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyidEqualTo(String value) {
            addCriterion("PROPERTYID =", value, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidNotEqualTo(String value) {
            addCriterion("PROPERTYID <>", value, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidGreaterThan(String value) {
            addCriterion("PROPERTYID >", value, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidGreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTYID >=", value, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidLessThan(String value) {
            addCriterion("PROPERTYID <", value, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidLessThanOrEqualTo(String value) {
            addCriterion("PROPERTYID <=", value, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidLike(String value) {
            addCriterion("PROPERTYID like", value, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidNotLike(String value) {
            addCriterion("PROPERTYID not like", value, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidIn(List<String> values) {
            addCriterion("PROPERTYID in", values, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidNotIn(List<String> values) {
            addCriterion("PROPERTYID not in", values, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidBetween(String value1, String value2) {
            addCriterion("PROPERTYID between", value1, value2, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertyidNotBetween(String value1, String value2) {
            addCriterion("PROPERTYID not between", value1, value2, "propertyid");
            return (Criteria) this;
        }

        public Criteria andPropertynameIsNull() {
            addCriterion("PROPERTYNAME is null");
            return (Criteria) this;
        }

        public Criteria andPropertynameIsNotNull() {
            addCriterion("PROPERTYNAME is not null");
            return (Criteria) this;
        }

        public Criteria andPropertynameEqualTo(String value) {
            addCriterion("PROPERTYNAME =", value, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameNotEqualTo(String value) {
            addCriterion("PROPERTYNAME <>", value, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameGreaterThan(String value) {
            addCriterion("PROPERTYNAME >", value, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameGreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTYNAME >=", value, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameLessThan(String value) {
            addCriterion("PROPERTYNAME <", value, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameLessThanOrEqualTo(String value) {
            addCriterion("PROPERTYNAME <=", value, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameLike(String value) {
            addCriterion("PROPERTYNAME like", value, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameNotLike(String value) {
            addCriterion("PROPERTYNAME not like", value, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameIn(List<String> values) {
            addCriterion("PROPERTYNAME in", values, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameNotIn(List<String> values) {
            addCriterion("PROPERTYNAME not in", values, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameBetween(String value1, String value2) {
            addCriterion("PROPERTYNAME between", value1, value2, "propertyname");
            return (Criteria) this;
        }

        public Criteria andPropertynameNotBetween(String value1, String value2) {
            addCriterion("PROPERTYNAME not between", value1, value2, "propertyname");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidIsNull() {
            addCriterion("EQUIPMENTCLASSID is null");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidIsNotNull() {
            addCriterion("EQUIPMENTCLASSID is not null");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidEqualTo(String value) {
            addCriterion("EQUIPMENTCLASSID =", value, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidNotEqualTo(String value) {
            addCriterion("EQUIPMENTCLASSID <>", value, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidGreaterThan(String value) {
            addCriterion("EQUIPMENTCLASSID >", value, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidGreaterThanOrEqualTo(String value) {
            addCriterion("EQUIPMENTCLASSID >=", value, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidLessThan(String value) {
            addCriterion("EQUIPMENTCLASSID <", value, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidLessThanOrEqualTo(String value) {
            addCriterion("EQUIPMENTCLASSID <=", value, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidLike(String value) {
            addCriterion("EQUIPMENTCLASSID like", value, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidNotLike(String value) {
            addCriterion("EQUIPMENTCLASSID not like", value, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidIn(List<String> values) {
            addCriterion("EQUIPMENTCLASSID in", values, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidNotIn(List<String> values) {
            addCriterion("EQUIPMENTCLASSID not in", values, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidBetween(String value1, String value2) {
            addCriterion("EQUIPMENTCLASSID between", value1, value2, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andEquipmentclassidNotBetween(String value1, String value2) {
            addCriterion("EQUIPMENTCLASSID not between", value1, value2, "equipmentclassid");
            return (Criteria) this;
        }

        public Criteria andPropertygroupidIsNull() {
            addCriterion("PROPERTYGROUPID is null");
            return (Criteria) this;
        }

        public Criteria andPropertygroupidIsNotNull() {
            addCriterion("PROPERTYGROUPID is not null");
            return (Criteria) this;
        }

        public Criteria andPropertygroupidEqualTo(String value) {
            addCriterion("PROPERTYGROUPID =", value, "propertygroupid");
            return (Criteria) this;
        }

        public Criteria andPropertygroupidNotEqualTo(String value) {
            addCriterion("PROPERTYGROUPID <>", value, "propertygroupid");
            return (Criteria) this;
        }

        public Criteria andPropertygroupidGreaterThan(String value) {
            addCriterion("PROPERTYGROUPID >", value, "propertygroupid");
            return (Criteria) this;
        }

        public Criteria andPropertygroupidGreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTYGROUPID >=", value, "propertygroupid");
            return (Criteria) this;
        }

        public Criteria andPropertygroupidLessThan(String value) {
            addCriterion("PROPERTYGROUPID <", value, "propertygroupid");
            return (Criteria) this;
        }

        public Criteria andPropertygroupidLessThanOrEqualTo(String value) {
            addCriterion("PROPERTYGROUPID <=", value, "propertygroupid");
            return (Criteria) this;
        }

        public Criteria andPropertygroupidLike(String value) {
            addCriterion("PROPERTYGROUPID like", value, "propertygroupid");
            return (Criteria) this;
        }

        public Criteria andPropertygroupidNotLike(String value) {
            addCriterion("PROPERTYGROUPID not like", value, "propertygroupid");
            return (Criteria) this;
        }

        public Criteria andPropertygroupidIn(List<String> values) {
            addCriterion("PROPERTYGROUPID in", values, "propertygroupid");
            return (Criteria) this;
        }

        public Criteria andPropertygroupidNotIn(List<String> values) {
            addCriterion("PROPERTYGROUPID not in", values, "propertygroupid");
            return (Criteria) this;
        }

        public Criteria andPropertygroupidBetween(String value1, String value2) {
            addCriterion("PROPERTYGROUPID between", value1, value2, "propertygroupid");
            return (Criteria) this;
        }

        public Criteria andPropertygroupidNotBetween(String value1, String value2) {
            addCriterion("PROPERTYGROUPID not between", value1, value2, "propertygroupid");
            return (Criteria) this;
        }

        public Criteria andDatatypeIsNull() {
            addCriterion("DATATYPE is null");
            return (Criteria) this;
        }

        public Criteria andDatatypeIsNotNull() {
            addCriterion("DATATYPE is not null");
            return (Criteria) this;
        }

        public Criteria andDatatypeEqualTo(String value) {
            addCriterion("DATATYPE =", value, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeNotEqualTo(String value) {
            addCriterion("DATATYPE <>", value, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeGreaterThan(String value) {
            addCriterion("DATATYPE >", value, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeGreaterThanOrEqualTo(String value) {
            addCriterion("DATATYPE >=", value, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeLessThan(String value) {
            addCriterion("DATATYPE <", value, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeLessThanOrEqualTo(String value) {
            addCriterion("DATATYPE <=", value, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeLike(String value) {
            addCriterion("DATATYPE like", value, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeNotLike(String value) {
            addCriterion("DATATYPE not like", value, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeIn(List<String> values) {
            addCriterion("DATATYPE in", values, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeNotIn(List<String> values) {
            addCriterion("DATATYPE not in", values, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeBetween(String value1, String value2) {
            addCriterion("DATATYPE between", value1, value2, "datatype");
            return (Criteria) this;
        }

        public Criteria andDatatypeNotBetween(String value1, String value2) {
            addCriterion("DATATYPE not between", value1, value2, "datatype");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueIsNull() {
            addCriterion("DEFAULTVALUE is null");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueIsNotNull() {
            addCriterion("DEFAULTVALUE is not null");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueEqualTo(String value) {
            addCriterion("DEFAULTVALUE =", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueNotEqualTo(String value) {
            addCriterion("DEFAULTVALUE <>", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueGreaterThan(String value) {
            addCriterion("DEFAULTVALUE >", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueGreaterThanOrEqualTo(String value) {
            addCriterion("DEFAULTVALUE >=", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueLessThan(String value) {
            addCriterion("DEFAULTVALUE <", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueLessThanOrEqualTo(String value) {
            addCriterion("DEFAULTVALUE <=", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueLike(String value) {
            addCriterion("DEFAULTVALUE like", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueNotLike(String value) {
            addCriterion("DEFAULTVALUE not like", value, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueIn(List<String> values) {
            addCriterion("DEFAULTVALUE in", values, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueNotIn(List<String> values) {
            addCriterion("DEFAULTVALUE not in", values, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueBetween(String value1, String value2) {
            addCriterion("DEFAULTVALUE between", value1, value2, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andDefaultvalueNotBetween(String value1, String value2) {
            addCriterion("DEFAULTVALUE not between", value1, value2, "defaultvalue");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourceIsNull() {
            addCriterion("PROPERTYVALUESOURCE is null");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourceIsNotNull() {
            addCriterion("PROPERTYVALUESOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourceEqualTo(String value) {
            addCriterion("PROPERTYVALUESOURCE =", value, "propertyvaluesource");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourceNotEqualTo(String value) {
            addCriterion("PROPERTYVALUESOURCE <>", value, "propertyvaluesource");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourceGreaterThan(String value) {
            addCriterion("PROPERTYVALUESOURCE >", value, "propertyvaluesource");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourceGreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTYVALUESOURCE >=", value, "propertyvaluesource");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourceLessThan(String value) {
            addCriterion("PROPERTYVALUESOURCE <", value, "propertyvaluesource");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourceLessThanOrEqualTo(String value) {
            addCriterion("PROPERTYVALUESOURCE <=", value, "propertyvaluesource");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourceLike(String value) {
            addCriterion("PROPERTYVALUESOURCE like", value, "propertyvaluesource");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourceNotLike(String value) {
            addCriterion("PROPERTYVALUESOURCE not like", value, "propertyvaluesource");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourceIn(List<String> values) {
            addCriterion("PROPERTYVALUESOURCE in", values, "propertyvaluesource");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourceNotIn(List<String> values) {
            addCriterion("PROPERTYVALUESOURCE not in", values, "propertyvaluesource");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourceBetween(String value1, String value2) {
            addCriterion("PROPERTYVALUESOURCE between", value1, value2, "propertyvaluesource");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourceNotBetween(String value1, String value2) {
            addCriterion("PROPERTYVALUESOURCE not between", value1, value2, "propertyvaluesource");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourcecfgIdIsNull() {
            addCriterion("PROPERTYVALUESOURCECFG_ID is null");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourcecfgIdIsNotNull() {
            addCriterion("PROPERTYVALUESOURCECFG_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourcecfgIdEqualTo(String value) {
            addCriterion("PROPERTYVALUESOURCECFG_ID =", value, "propertyvaluesourcecfgId");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourcecfgIdNotEqualTo(String value) {
            addCriterion("PROPERTYVALUESOURCECFG_ID <>", value, "propertyvaluesourcecfgId");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourcecfgIdGreaterThan(String value) {
            addCriterion("PROPERTYVALUESOURCECFG_ID >", value, "propertyvaluesourcecfgId");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourcecfgIdGreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTYVALUESOURCECFG_ID >=", value, "propertyvaluesourcecfgId");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourcecfgIdLessThan(String value) {
            addCriterion("PROPERTYVALUESOURCECFG_ID <", value, "propertyvaluesourcecfgId");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourcecfgIdLessThanOrEqualTo(String value) {
            addCriterion("PROPERTYVALUESOURCECFG_ID <=", value, "propertyvaluesourcecfgId");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourcecfgIdLike(String value) {
            addCriterion("PROPERTYVALUESOURCECFG_ID like", value, "propertyvaluesourcecfgId");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourcecfgIdNotLike(String value) {
            addCriterion("PROPERTYVALUESOURCECFG_ID not like", value, "propertyvaluesourcecfgId");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourcecfgIdIn(List<String> values) {
            addCriterion("PROPERTYVALUESOURCECFG_ID in", values, "propertyvaluesourcecfgId");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourcecfgIdNotIn(List<String> values) {
            addCriterion("PROPERTYVALUESOURCECFG_ID not in", values, "propertyvaluesourcecfgId");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourcecfgIdBetween(String value1, String value2) {
            addCriterion("PROPERTYVALUESOURCECFG_ID between", value1, value2, "propertyvaluesourcecfgId");
            return (Criteria) this;
        }

        public Criteria andPropertyvaluesourcecfgIdNotBetween(String value1, String value2) {
            addCriterion("PROPERTYVALUESOURCECFG_ID not between", value1, value2, "propertyvaluesourcecfgId");
            return (Criteria) this;
        }

        public Criteria andEngrunitsIsNull() {
            addCriterion("ENGRUNITS is null");
            return (Criteria) this;
        }

        public Criteria andEngrunitsIsNotNull() {
            addCriterion("ENGRUNITS is not null");
            return (Criteria) this;
        }

        public Criteria andEngrunitsEqualTo(String value) {
            addCriterion("ENGRUNITS =", value, "engrunits");
            return (Criteria) this;
        }

        public Criteria andEngrunitsNotEqualTo(String value) {
            addCriterion("ENGRUNITS <>", value, "engrunits");
            return (Criteria) this;
        }

        public Criteria andEngrunitsGreaterThan(String value) {
            addCriterion("ENGRUNITS >", value, "engrunits");
            return (Criteria) this;
        }

        public Criteria andEngrunitsGreaterThanOrEqualTo(String value) {
            addCriterion("ENGRUNITS >=", value, "engrunits");
            return (Criteria) this;
        }

        public Criteria andEngrunitsLessThan(String value) {
            addCriterion("ENGRUNITS <", value, "engrunits");
            return (Criteria) this;
        }

        public Criteria andEngrunitsLessThanOrEqualTo(String value) {
            addCriterion("ENGRUNITS <=", value, "engrunits");
            return (Criteria) this;
        }

        public Criteria andEngrunitsLike(String value) {
            addCriterion("ENGRUNITS like", value, "engrunits");
            return (Criteria) this;
        }

        public Criteria andEngrunitsNotLike(String value) {
            addCriterion("ENGRUNITS not like", value, "engrunits");
            return (Criteria) this;
        }

        public Criteria andEngrunitsIn(List<String> values) {
            addCriterion("ENGRUNITS in", values, "engrunits");
            return (Criteria) this;
        }

        public Criteria andEngrunitsNotIn(List<String> values) {
            addCriterion("ENGRUNITS not in", values, "engrunits");
            return (Criteria) this;
        }

        public Criteria andEngrunitsBetween(String value1, String value2) {
            addCriterion("ENGRUNITS between", value1, value2, "engrunits");
            return (Criteria) this;
        }

        public Criteria andEngrunitsNotBetween(String value1, String value2) {
            addCriterion("ENGRUNITS not between", value1, value2, "engrunits");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("DESCRIPTION is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("DESCRIPTION is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("DESCRIPTION =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("DESCRIPTION <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("DESCRIPTION >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("DESCRIPTION <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("DESCRIPTION <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("DESCRIPTION like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("DESCRIPTION not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("DESCRIPTION in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("DESCRIPTION not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("DESCRIPTION between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("DESCRIPTION not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNull() {
            addCriterion("AUTHOR is null");
            return (Criteria) this;
        }

        public Criteria andAuthorIsNotNull() {
            addCriterion("AUTHOR is not null");
            return (Criteria) this;
        }

        public Criteria andAuthorEqualTo(String value) {
            addCriterion("AUTHOR =", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotEqualTo(String value) {
            addCriterion("AUTHOR <>", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThan(String value) {
            addCriterion("AUTHOR >", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorGreaterThanOrEqualTo(String value) {
            addCriterion("AUTHOR >=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThan(String value) {
            addCriterion("AUTHOR <", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLessThanOrEqualTo(String value) {
            addCriterion("AUTHOR <=", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorLike(String value) {
            addCriterion("AUTHOR like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotLike(String value) {
            addCriterion("AUTHOR not like", value, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorIn(List<String> values) {
            addCriterion("AUTHOR in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotIn(List<String> values) {
            addCriterion("AUTHOR not in", values, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorBetween(String value1, String value2) {
            addCriterion("AUTHOR between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andAuthorNotBetween(String value1, String value2) {
            addCriterion("AUTHOR not between", value1, value2, "author");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNull() {
            addCriterion("CREATEDATE is null");
            return (Criteria) this;
        }

        public Criteria andCreatedateIsNotNull() {
            addCriterion("CREATEDATE is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedateEqualTo(Date value) {
            addCriterion("CREATEDATE =", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotEqualTo(Date value) {
            addCriterion("CREATEDATE <>", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThan(Date value) {
            addCriterion("CREATEDATE >", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE >=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThan(Date value) {
            addCriterion("CREATEDATE <", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateLessThanOrEqualTo(Date value) {
            addCriterion("CREATEDATE <=", value, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateIn(List<Date> values) {
            addCriterion("CREATEDATE in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotIn(List<Date> values) {
            addCriterion("CREATEDATE not in", values, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andCreatedateNotBetween(Date value1, Date value2) {
            addCriterion("CREATEDATE not between", value1, value2, "createdate");
            return (Criteria) this;
        }

        public Criteria andApprovedbyIsNull() {
            addCriterion("APPROVEDBY is null");
            return (Criteria) this;
        }

        public Criteria andApprovedbyIsNotNull() {
            addCriterion("APPROVEDBY is not null");
            return (Criteria) this;
        }

        public Criteria andApprovedbyEqualTo(String value) {
            addCriterion("APPROVEDBY =", value, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyNotEqualTo(String value) {
            addCriterion("APPROVEDBY <>", value, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyGreaterThan(String value) {
            addCriterion("APPROVEDBY >", value, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyGreaterThanOrEqualTo(String value) {
            addCriterion("APPROVEDBY >=", value, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyLessThan(String value) {
            addCriterion("APPROVEDBY <", value, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyLessThanOrEqualTo(String value) {
            addCriterion("APPROVEDBY <=", value, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyLike(String value) {
            addCriterion("APPROVEDBY like", value, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyNotLike(String value) {
            addCriterion("APPROVEDBY not like", value, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyIn(List<String> values) {
            addCriterion("APPROVEDBY in", values, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyNotIn(List<String> values) {
            addCriterion("APPROVEDBY not in", values, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyBetween(String value1, String value2) {
            addCriterion("APPROVEDBY between", value1, value2, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovedbyNotBetween(String value1, String value2) {
            addCriterion("APPROVEDBY not between", value1, value2, "approvedby");
            return (Criteria) this;
        }

        public Criteria andApprovaldateIsNull() {
            addCriterion("APPROVALDATE is null");
            return (Criteria) this;
        }

        public Criteria andApprovaldateIsNotNull() {
            addCriterion("APPROVALDATE is not null");
            return (Criteria) this;
        }

        public Criteria andApprovaldateEqualTo(Date value) {
            addCriterion("APPROVALDATE =", value, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateNotEqualTo(Date value) {
            addCriterion("APPROVALDATE <>", value, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateGreaterThan(Date value) {
            addCriterion("APPROVALDATE >", value, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateGreaterThanOrEqualTo(Date value) {
            addCriterion("APPROVALDATE >=", value, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateLessThan(Date value) {
            addCriterion("APPROVALDATE <", value, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateLessThanOrEqualTo(Date value) {
            addCriterion("APPROVALDATE <=", value, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateIn(List<Date> values) {
            addCriterion("APPROVALDATE in", values, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateNotIn(List<Date> values) {
            addCriterion("APPROVALDATE not in", values, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateBetween(Date value1, Date value2) {
            addCriterion("APPROVALDATE between", value1, value2, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andApprovaldateNotBetween(Date value1, Date value2) {
            addCriterion("APPROVALDATE not between", value1, value2, "approvaldate");
            return (Criteria) this;
        }

        public Criteria andLinageIsNull() {
            addCriterion("LINAGE is null");
            return (Criteria) this;
        }

        public Criteria andLinageIsNotNull() {
            addCriterion("LINAGE is not null");
            return (Criteria) this;
        }

        public Criteria andLinageEqualTo(Integer value) {
            addCriterion("LINAGE =", value, "linage");
            return (Criteria) this;
        }

        public Criteria andLinageNotEqualTo(Integer value) {
            addCriterion("LINAGE <>", value, "linage");
            return (Criteria) this;
        }

        public Criteria andLinageGreaterThan(Integer value) {
            addCriterion("LINAGE >", value, "linage");
            return (Criteria) this;
        }

        public Criteria andLinageGreaterThanOrEqualTo(Integer value) {
            addCriterion("LINAGE >=", value, "linage");
            return (Criteria) this;
        }

        public Criteria andLinageLessThan(Integer value) {
            addCriterion("LINAGE <", value, "linage");
            return (Criteria) this;
        }

        public Criteria andLinageLessThanOrEqualTo(Integer value) {
            addCriterion("LINAGE <=", value, "linage");
            return (Criteria) this;
        }

        public Criteria andLinageIn(List<Integer> values) {
            addCriterion("LINAGE in", values, "linage");
            return (Criteria) this;
        }

        public Criteria andLinageNotIn(List<Integer> values) {
            addCriterion("LINAGE not in", values, "linage");
            return (Criteria) this;
        }

        public Criteria andLinageBetween(Integer value1, Integer value2) {
            addCriterion("LINAGE between", value1, value2, "linage");
            return (Criteria) this;
        }

        public Criteria andLinageNotBetween(Integer value1, Integer value2) {
            addCriterion("LINAGE not between", value1, value2, "linage");
            return (Criteria) this;
        }

        public Criteria andPropertyflagIsNull() {
            addCriterion("PROPERTYFLAG is null");
            return (Criteria) this;
        }

        public Criteria andPropertyflagIsNotNull() {
            addCriterion("PROPERTYFLAG is not null");
            return (Criteria) this;
        }

        public Criteria andPropertyflagEqualTo(String value) {
            addCriterion("PROPERTYFLAG =", value, "propertyflag");
            return (Criteria) this;
        }

        public Criteria andPropertyflagNotEqualTo(String value) {
            addCriterion("PROPERTYFLAG <>", value, "propertyflag");
            return (Criteria) this;
        }

        public Criteria andPropertyflagGreaterThan(String value) {
            addCriterion("PROPERTYFLAG >", value, "propertyflag");
            return (Criteria) this;
        }

        public Criteria andPropertyflagGreaterThanOrEqualTo(String value) {
            addCriterion("PROPERTYFLAG >=", value, "propertyflag");
            return (Criteria) this;
        }

        public Criteria andPropertyflagLessThan(String value) {
            addCriterion("PROPERTYFLAG <", value, "propertyflag");
            return (Criteria) this;
        }

        public Criteria andPropertyflagLessThanOrEqualTo(String value) {
            addCriterion("PROPERTYFLAG <=", value, "propertyflag");
            return (Criteria) this;
        }

        public Criteria andPropertyflagLike(String value) {
            addCriterion("PROPERTYFLAG like", value, "propertyflag");
            return (Criteria) this;
        }

        public Criteria andPropertyflagNotLike(String value) {
            addCriterion("PROPERTYFLAG not like", value, "propertyflag");
            return (Criteria) this;
        }

        public Criteria andPropertyflagIn(List<String> values) {
            addCriterion("PROPERTYFLAG in", values, "propertyflag");
            return (Criteria) this;
        }

        public Criteria andPropertyflagNotIn(List<String> values) {
            addCriterion("PROPERTYFLAG not in", values, "propertyflag");
            return (Criteria) this;
        }

        public Criteria andPropertyflagBetween(String value1, String value2) {
            addCriterion("PROPERTYFLAG between", value1, value2, "propertyflag");
            return (Criteria) this;
        }

        public Criteria andPropertyflagNotBetween(String value1, String value2) {
            addCriterion("PROPERTYFLAG not between", value1, value2, "propertyflag");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated do_not_delete_during_merge Tue May 30 17:21:52 GMT+08:00 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table ems_equipmentclassproperty
     *
     * @mbg.generated Tue May 30 17:21:52 GMT+08:00 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}