package com.example.repository.model;

import java.util.Date;

public class EmsEquipmentclassproperty {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclassproperty.PROPERTYID
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String propertyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclassproperty.PROPERTYNAME
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String propertyname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclassproperty.EQUIPMENTCLASSID
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String equipmentclassid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclassproperty.PROPERTYGROUPID
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String propertygroupid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclassproperty.DATATYPE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String datatype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclassproperty.DEFAULTVALUE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String defaultvalue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclassproperty.PROPERTYVALUESOURCE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String propertyvaluesource;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclassproperty.PROPERTYVALUESOURCECFG_ID
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String propertyvaluesourcecfgId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclassproperty.ENGRUNITS
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String engrunits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclassproperty.DESCRIPTION
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclassproperty.AUTHOR
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclassproperty.CREATEDATE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private Date createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclassproperty.APPROVEDBY
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String approvedby;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclassproperty.APPROVALDATE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private Date approvaldate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclassproperty.LINAGE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private Integer linage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ems_equipmentclassproperty.PROPERTYFLAG
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    private String propertyflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclassproperty.PROPERTYID
     *
     * @return the value of ems_equipmentclassproperty.PROPERTYID
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getPropertyid() {
        return propertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclassproperty.PROPERTYID
     *
     * @param propertyid the value for ems_equipmentclassproperty.PROPERTYID
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setPropertyid(String propertyid) {
        this.propertyid = propertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclassproperty.PROPERTYNAME
     *
     * @return the value of ems_equipmentclassproperty.PROPERTYNAME
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getPropertyname() {
        return propertyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclassproperty.PROPERTYNAME
     *
     * @param propertyname the value for ems_equipmentclassproperty.PROPERTYNAME
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setPropertyname(String propertyname) {
        this.propertyname = propertyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclassproperty.EQUIPMENTCLASSID
     *
     * @return the value of ems_equipmentclassproperty.EQUIPMENTCLASSID
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getEquipmentclassid() {
        return equipmentclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclassproperty.EQUIPMENTCLASSID
     *
     * @param equipmentclassid the value for ems_equipmentclassproperty.EQUIPMENTCLASSID
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setEquipmentclassid(String equipmentclassid) {
        this.equipmentclassid = equipmentclassid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclassproperty.PROPERTYGROUPID
     *
     * @return the value of ems_equipmentclassproperty.PROPERTYGROUPID
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getPropertygroupid() {
        return propertygroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclassproperty.PROPERTYGROUPID
     *
     * @param propertygroupid the value for ems_equipmentclassproperty.PROPERTYGROUPID
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setPropertygroupid(String propertygroupid) {
        this.propertygroupid = propertygroupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclassproperty.DATATYPE
     *
     * @return the value of ems_equipmentclassproperty.DATATYPE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getDatatype() {
        return datatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclassproperty.DATATYPE
     *
     * @param datatype the value for ems_equipmentclassproperty.DATATYPE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setDatatype(String datatype) {
        this.datatype = datatype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclassproperty.DEFAULTVALUE
     *
     * @return the value of ems_equipmentclassproperty.DEFAULTVALUE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getDefaultvalue() {
        return defaultvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclassproperty.DEFAULTVALUE
     *
     * @param defaultvalue the value for ems_equipmentclassproperty.DEFAULTVALUE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setDefaultvalue(String defaultvalue) {
        this.defaultvalue = defaultvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclassproperty.PROPERTYVALUESOURCE
     *
     * @return the value of ems_equipmentclassproperty.PROPERTYVALUESOURCE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getPropertyvaluesource() {
        return propertyvaluesource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclassproperty.PROPERTYVALUESOURCE
     *
     * @param propertyvaluesource the value for ems_equipmentclassproperty.PROPERTYVALUESOURCE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setPropertyvaluesource(String propertyvaluesource) {
        this.propertyvaluesource = propertyvaluesource;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclassproperty.PROPERTYVALUESOURCECFG_ID
     *
     * @return the value of ems_equipmentclassproperty.PROPERTYVALUESOURCECFG_ID
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getPropertyvaluesourcecfgId() {
        return propertyvaluesourcecfgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclassproperty.PROPERTYVALUESOURCECFG_ID
     *
     * @param propertyvaluesourcecfgId the value for ems_equipmentclassproperty.PROPERTYVALUESOURCECFG_ID
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setPropertyvaluesourcecfgId(String propertyvaluesourcecfgId) {
        this.propertyvaluesourcecfgId = propertyvaluesourcecfgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclassproperty.ENGRUNITS
     *
     * @return the value of ems_equipmentclassproperty.ENGRUNITS
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getEngrunits() {
        return engrunits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclassproperty.ENGRUNITS
     *
     * @param engrunits the value for ems_equipmentclassproperty.ENGRUNITS
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setEngrunits(String engrunits) {
        this.engrunits = engrunits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclassproperty.DESCRIPTION
     *
     * @return the value of ems_equipmentclassproperty.DESCRIPTION
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclassproperty.DESCRIPTION
     *
     * @param description the value for ems_equipmentclassproperty.DESCRIPTION
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclassproperty.AUTHOR
     *
     * @return the value of ems_equipmentclassproperty.AUTHOR
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclassproperty.AUTHOR
     *
     * @param author the value for ems_equipmentclassproperty.AUTHOR
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclassproperty.CREATEDATE
     *
     * @return the value of ems_equipmentclassproperty.CREATEDATE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclassproperty.CREATEDATE
     *
     * @param createdate the value for ems_equipmentclassproperty.CREATEDATE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclassproperty.APPROVEDBY
     *
     * @return the value of ems_equipmentclassproperty.APPROVEDBY
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getApprovedby() {
        return approvedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclassproperty.APPROVEDBY
     *
     * @param approvedby the value for ems_equipmentclassproperty.APPROVEDBY
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setApprovedby(String approvedby) {
        this.approvedby = approvedby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclassproperty.APPROVALDATE
     *
     * @return the value of ems_equipmentclassproperty.APPROVALDATE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public Date getApprovaldate() {
        return approvaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclassproperty.APPROVALDATE
     *
     * @param approvaldate the value for ems_equipmentclassproperty.APPROVALDATE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setApprovaldate(Date approvaldate) {
        this.approvaldate = approvaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclassproperty.LINAGE
     *
     * @return the value of ems_equipmentclassproperty.LINAGE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public Integer getLinage() {
        return linage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclassproperty.LINAGE
     *
     * @param linage the value for ems_equipmentclassproperty.LINAGE
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setLinage(Integer linage) {
        this.linage = linage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ems_equipmentclassproperty.PROPERTYFLAG
     *
     * @return the value of ems_equipmentclassproperty.PROPERTYFLAG
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public String getPropertyflag() {
        return propertyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ems_equipmentclassproperty.PROPERTYFLAG
     *
     * @param propertyflag the value for ems_equipmentclassproperty.PROPERTYFLAG
     *
     * @mbg.generated Wed Jan 11 23:20:16 GMT+08:00 2023
     */
    public void setPropertyflag(String propertyflag) {
        this.propertyflag = propertyflag;
    }
}