package com.example.repository.model;

import java.util.Date;

public class EmsPreheatRunTime {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMS_PREHEAT_RUN_TIME.date
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMS_PREHEAT_RUN_TIME.record_everyday_p1
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    private Long recordEverydayP1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMS_PREHEAT_RUN_TIME.record_everyday_p2
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    private Long recordEverydayP2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMS_PREHEAT_RUN_TIME.record_everyday_p3
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    private Long recordEverydayP3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMS_PREHEAT_RUN_TIME.record_everyday_p4
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    private Long recordEverydayP4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMS_PREHEAT_RUN_TIME.record_everyday_p5
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    private Long recordEverydayP5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMS_PREHEAT_RUN_TIME.record_everyday_p6
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    private Long recordEverydayP6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMS_PREHEAT_RUN_TIME.record_everyday_p7
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    private Long recordEverydayP7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMS_PREHEAT_RUN_TIME.record_everyday_p8
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    private Long recordEverydayP8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column EMS_PREHEAT_RUN_TIME.record_date
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    private Date recordDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMS_PREHEAT_RUN_TIME.date
     *
     * @return the value of EMS_PREHEAT_RUN_TIME.date
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMS_PREHEAT_RUN_TIME.date
     *
     * @param date the value for EMS_PREHEAT_RUN_TIME.date
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMS_PREHEAT_RUN_TIME.record_everyday_p1
     *
     * @return the value of EMS_PREHEAT_RUN_TIME.record_everyday_p1
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public Long getRecordEverydayP1() {
        return recordEverydayP1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMS_PREHEAT_RUN_TIME.record_everyday_p1
     *
     * @param recordEverydayP1 the value for EMS_PREHEAT_RUN_TIME.record_everyday_p1
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public void setRecordEverydayP1(Long recordEverydayP1) {
        this.recordEverydayP1 = recordEverydayP1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMS_PREHEAT_RUN_TIME.record_everyday_p2
     *
     * @return the value of EMS_PREHEAT_RUN_TIME.record_everyday_p2
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public Long getRecordEverydayP2() {
        return recordEverydayP2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMS_PREHEAT_RUN_TIME.record_everyday_p2
     *
     * @param recordEverydayP2 the value for EMS_PREHEAT_RUN_TIME.record_everyday_p2
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public void setRecordEverydayP2(Long recordEverydayP2) {
        this.recordEverydayP2 = recordEverydayP2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMS_PREHEAT_RUN_TIME.record_everyday_p3
     *
     * @return the value of EMS_PREHEAT_RUN_TIME.record_everyday_p3
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public Long getRecordEverydayP3() {
        return recordEverydayP3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMS_PREHEAT_RUN_TIME.record_everyday_p3
     *
     * @param recordEverydayP3 the value for EMS_PREHEAT_RUN_TIME.record_everyday_p3
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public void setRecordEverydayP3(Long recordEverydayP3) {
        this.recordEverydayP3 = recordEverydayP3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMS_PREHEAT_RUN_TIME.record_everyday_p4
     *
     * @return the value of EMS_PREHEAT_RUN_TIME.record_everyday_p4
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public Long getRecordEverydayP4() {
        return recordEverydayP4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMS_PREHEAT_RUN_TIME.record_everyday_p4
     *
     * @param recordEverydayP4 the value for EMS_PREHEAT_RUN_TIME.record_everyday_p4
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public void setRecordEverydayP4(Long recordEverydayP4) {
        this.recordEverydayP4 = recordEverydayP4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMS_PREHEAT_RUN_TIME.record_everyday_p5
     *
     * @return the value of EMS_PREHEAT_RUN_TIME.record_everyday_p5
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public Long getRecordEverydayP5() {
        return recordEverydayP5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMS_PREHEAT_RUN_TIME.record_everyday_p5
     *
     * @param recordEverydayP5 the value for EMS_PREHEAT_RUN_TIME.record_everyday_p5
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public void setRecordEverydayP5(Long recordEverydayP5) {
        this.recordEverydayP5 = recordEverydayP5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMS_PREHEAT_RUN_TIME.record_everyday_p6
     *
     * @return the value of EMS_PREHEAT_RUN_TIME.record_everyday_p6
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public Long getRecordEverydayP6() {
        return recordEverydayP6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMS_PREHEAT_RUN_TIME.record_everyday_p6
     *
     * @param recordEverydayP6 the value for EMS_PREHEAT_RUN_TIME.record_everyday_p6
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public void setRecordEverydayP6(Long recordEverydayP6) {
        this.recordEverydayP6 = recordEverydayP6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMS_PREHEAT_RUN_TIME.record_everyday_p7
     *
     * @return the value of EMS_PREHEAT_RUN_TIME.record_everyday_p7
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public Long getRecordEverydayP7() {
        return recordEverydayP7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMS_PREHEAT_RUN_TIME.record_everyday_p7
     *
     * @param recordEverydayP7 the value for EMS_PREHEAT_RUN_TIME.record_everyday_p7
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public void setRecordEverydayP7(Long recordEverydayP7) {
        this.recordEverydayP7 = recordEverydayP7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMS_PREHEAT_RUN_TIME.record_everyday_p8
     *
     * @return the value of EMS_PREHEAT_RUN_TIME.record_everyday_p8
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public Long getRecordEverydayP8() {
        return recordEverydayP8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMS_PREHEAT_RUN_TIME.record_everyday_p8
     *
     * @param recordEverydayP8 the value for EMS_PREHEAT_RUN_TIME.record_everyday_p8
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public void setRecordEverydayP8(Long recordEverydayP8) {
        this.recordEverydayP8 = recordEverydayP8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column EMS_PREHEAT_RUN_TIME.record_date
     *
     * @return the value of EMS_PREHEAT_RUN_TIME.record_date
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public Date getRecordDate() {
        return recordDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column EMS_PREHEAT_RUN_TIME.record_date
     *
     * @param recordDate the value for EMS_PREHEAT_RUN_TIME.record_date
     *
     * @mbg.generated Fri May 16 11:19:14 CST 2025
     */
    public void setRecordDate(Date recordDate) {
        this.recordDate = recordDate;
    }
}