package com.example.repository.model;

public class PdsEquipproperty {
    private Object value;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.PROPERTYID
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private String propertyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.EQUIPMENTID
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private String equipmentid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.PROPERTYNAME
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private String propertyname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.PROPERTYVALUE
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private String propertyvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.ENGRUNITS
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private String engrunits;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.ISOPCONLINE
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private Integer isopconline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.TAGADDRESS
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private String tagaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.PRECISION
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private Long precision;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.DESCRIPTION
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.PROPERTYGROUP
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private Long propertygroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.ISINUSE
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private Integer isinuse;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.ISOUT
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private Integer isout;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.EDGECLIENTID
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private Long edgeclientid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.PROPERTYFLAG
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private String propertyflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.PROCESSVALUETYPE
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private Long processvaluetype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.PROCESSVALUECONDITION
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private String processvaluecondition;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.PROCESSPROPERTYID
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private String processpropertyid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.PROCESSVALUE
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private Long processvalue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.PROCESSDESCRIPTION
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private String processdescription;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PDS_EQUIPPROPERTY.ISPROCESSVALUERECORD
     *
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    private Long isprocessvaluerecord;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.PROPERTYID
     *
     * @return the value of PDS_EQUIPPROPERTY.PROPERTYID
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public String getPropertyid() {
        return propertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.PROPERTYID
     *
     * @param propertyid the value for PDS_EQUIPPROPERTY.PROPERTYID
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setPropertyid(String propertyid) {
        this.propertyid = propertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.EQUIPMENTID
     *
     * @return the value of PDS_EQUIPPROPERTY.EQUIPMENTID
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public String getEquipmentid() {
        return equipmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.EQUIPMENTID
     *
     * @param equipmentid the value for PDS_EQUIPPROPERTY.EQUIPMENTID
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setEquipmentid(String equipmentid) {
        this.equipmentid = equipmentid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.PROPERTYNAME
     *
     * @return the value of PDS_EQUIPPROPERTY.PROPERTYNAME
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public String getPropertyname() {
        return propertyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.PROPERTYNAME
     *
     * @param propertyname the value for PDS_EQUIPPROPERTY.PROPERTYNAME
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setPropertyname(String propertyname) {
        this.propertyname = propertyname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.PROPERTYVALUE
     *
     * @return the value of PDS_EQUIPPROPERTY.PROPERTYVALUE
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public String getPropertyvalue() {
        return propertyvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.PROPERTYVALUE
     *
     * @param propertyvalue the value for PDS_EQUIPPROPERTY.PROPERTYVALUE
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setPropertyvalue(String propertyvalue) {
        this.propertyvalue = propertyvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.ENGRUNITS
     *
     * @return the value of PDS_EQUIPPROPERTY.ENGRUNITS
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public String getEngrunits() {
        return engrunits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.ENGRUNITS
     *
     * @param engrunits the value for PDS_EQUIPPROPERTY.ENGRUNITS
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setEngrunits(String engrunits) {
        this.engrunits = engrunits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.ISOPCONLINE
     *
     * @return the value of PDS_EQUIPPROPERTY.ISOPCONLINE
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public Integer getIsopconline() {
        return isopconline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.ISOPCONLINE
     *
     * @param isopconline the value for PDS_EQUIPPROPERTY.ISOPCONLINE
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setIsopconline(Integer isopconline) {
        this.isopconline = isopconline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.TAGADDRESS
     *
     * @return the value of PDS_EQUIPPROPERTY.TAGADDRESS
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public String getTagaddress() {
        return tagaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.TAGADDRESS
     *
     * @param tagaddress the value for PDS_EQUIPPROPERTY.TAGADDRESS
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setTagaddress(String tagaddress) {
        this.tagaddress = tagaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.PRECISION
     *
     * @return the value of PDS_EQUIPPROPERTY.PRECISION
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public Long getPrecision() {
        return precision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.PRECISION
     *
     * @param precision the value for PDS_EQUIPPROPERTY.PRECISION
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setPrecision(Long precision) {
        this.precision = precision;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.DESCRIPTION
     *
     * @return the value of PDS_EQUIPPROPERTY.DESCRIPTION
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.DESCRIPTION
     *
     * @param description the value for PDS_EQUIPPROPERTY.DESCRIPTION
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.PROPERTYGROUP
     *
     * @return the value of PDS_EQUIPPROPERTY.PROPERTYGROUP
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public Long getPropertygroup() {
        return propertygroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.PROPERTYGROUP
     *
     * @param propertygroup the value for PDS_EQUIPPROPERTY.PROPERTYGROUP
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setPropertygroup(Long propertygroup) {
        this.propertygroup = propertygroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.ISINUSE
     *
     * @return the value of PDS_EQUIPPROPERTY.ISINUSE
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public Integer getIsinuse() {
        return isinuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.ISINUSE
     *
     * @param isinuse the value for PDS_EQUIPPROPERTY.ISINUSE
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setIsinuse(Integer isinuse) {
        this.isinuse = isinuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.ISOUT
     *
     * @return the value of PDS_EQUIPPROPERTY.ISOUT
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public Integer getIsout() {
        return isout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.ISOUT
     *
     * @param isout the value for PDS_EQUIPPROPERTY.ISOUT
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setIsout(Integer isout) {
        this.isout = isout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.EDGECLIENTID
     *
     * @return the value of PDS_EQUIPPROPERTY.EDGECLIENTID
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public Long getEdgeclientid() {
        return edgeclientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.EDGECLIENTID
     *
     * @param edgeclientid the value for PDS_EQUIPPROPERTY.EDGECLIENTID
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setEdgeclientid(Long edgeclientid) {
        this.edgeclientid = edgeclientid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.PROPERTYFLAG
     *
     * @return the value of PDS_EQUIPPROPERTY.PROPERTYFLAG
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public String getPropertyflag() {
        return propertyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.PROPERTYFLAG
     *
     * @param propertyflag the value for PDS_EQUIPPROPERTY.PROPERTYFLAG
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setPropertyflag(String propertyflag) {
        this.propertyflag = propertyflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.PROCESSVALUETYPE
     *
     * @return the value of PDS_EQUIPPROPERTY.PROCESSVALUETYPE
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public Long getProcessvaluetype() {
        return processvaluetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.PROCESSVALUETYPE
     *
     * @param processvaluetype the value for PDS_EQUIPPROPERTY.PROCESSVALUETYPE
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setProcessvaluetype(Long processvaluetype) {
        this.processvaluetype = processvaluetype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.PROCESSVALUECONDITION
     *
     * @return the value of PDS_EQUIPPROPERTY.PROCESSVALUECONDITION
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public String getProcessvaluecondition() {
        return processvaluecondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.PROCESSVALUECONDITION
     *
     * @param processvaluecondition the value for PDS_EQUIPPROPERTY.PROCESSVALUECONDITION
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setProcessvaluecondition(String processvaluecondition) {
        this.processvaluecondition = processvaluecondition;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.PROCESSPROPERTYID
     *
     * @return the value of PDS_EQUIPPROPERTY.PROCESSPROPERTYID
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public String getProcesspropertyid() {
        return processpropertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.PROCESSPROPERTYID
     *
     * @param processpropertyid the value for PDS_EQUIPPROPERTY.PROCESSPROPERTYID
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setProcesspropertyid(String processpropertyid) {
        this.processpropertyid = processpropertyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.PROCESSVALUE
     *
     * @return the value of PDS_EQUIPPROPERTY.PROCESSVALUE
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public Long getProcessvalue() {
        return processvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.PROCESSVALUE
     *
     * @param processvalue the value for PDS_EQUIPPROPERTY.PROCESSVALUE
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setProcessvalue(Long processvalue) {
        this.processvalue = processvalue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.PROCESSDESCRIPTION
     *
     * @return the value of PDS_EQUIPPROPERTY.PROCESSDESCRIPTION
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public String getProcessdescription() {
        return processdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.PROCESSDESCRIPTION
     *
     * @param processdescription the value for PDS_EQUIPPROPERTY.PROCESSDESCRIPTION
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setProcessdescription(String processdescription) {
        this.processdescription = processdescription;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PDS_EQUIPPROPERTY.ISPROCESSVALUERECORD
     *
     * @return the value of PDS_EQUIPPROPERTY.ISPROCESSVALUERECORD
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public Long getIsprocessvaluerecord() {
        return isprocessvaluerecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PDS_EQUIPPROPERTY.ISPROCESSVALUERECORD
     *
     * @param isprocessvaluerecord the value for PDS_EQUIPPROPERTY.ISPROCESSVALUERECORD
     * @mbg.generated Thu Nov 23 10:43:41 GMT+08:00 2023
     */
    public void setIsprocessvaluerecord(Long isprocessvaluerecord) {
        this.isprocessvaluerecord = isprocessvaluerecord;
    }

    public Object getValue() {
        return value;
    }

    public void setValue(Object value) {
        this.value = value;
    }
}