package com.example.repository.model;

import java.util.Date;

public class PrdCelltaskstoprecord extends PrdCelltaskstoprecordKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_CELLTASKSTOPRECORD.STOPENDTIME
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    private Date stopendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_CELLTASKSTOPRECORD.STOPTIMELONG
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    private Long stoptimelong;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_CELLTASKSTOPRECORD.EQUSTATUSID
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    private String equstatusid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_CELLTASKSTOPRECORD.STOPCLASS
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    private Short stopclass;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_CELLTASKSTOPRECORD.STOPTYPE
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    private String stoptype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_CELLTASKSTOPRECORD.STOPREASON
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    private String stopreason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_CELLTASKSTOPRECORD.STOPEQUCODE
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    private String stopequcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_CELLTASKSTOPRECORD.STOPEQUPART
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    private String stopequpart;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_CELLTASKSTOPRECORD.AUTHOR
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    private String author;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_CELLTASKSTOPRECORD.APPROVALDATE
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    private Date approvaldate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_CELLTASKSTOPRECORD.STOPDESC
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    private String stopdesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_CELLTASKSTOPRECORD.ISPUBED
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    private Long ispubed;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_CELLTASKSTOPRECORD.STOPENDTIME
     *
     * @return the value of PRD_CELLTASKSTOPRECORD.STOPENDTIME
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public Date getStopendtime() {
        return stopendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_CELLTASKSTOPRECORD.STOPENDTIME
     *
     * @param stopendtime the value for PRD_CELLTASKSTOPRECORD.STOPENDTIME
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public void setStopendtime(Date stopendtime) {
        this.stopendtime = stopendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_CELLTASKSTOPRECORD.STOPTIMELONG
     *
     * @return the value of PRD_CELLTASKSTOPRECORD.STOPTIMELONG
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public Long getStoptimelong() {
        return stoptimelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_CELLTASKSTOPRECORD.STOPTIMELONG
     *
     * @param stoptimelong the value for PRD_CELLTASKSTOPRECORD.STOPTIMELONG
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public void setStoptimelong(Long stoptimelong) {
        this.stoptimelong = stoptimelong;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_CELLTASKSTOPRECORD.EQUSTATUSID
     *
     * @return the value of PRD_CELLTASKSTOPRECORD.EQUSTATUSID
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public String getEqustatusid() {
        return equstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_CELLTASKSTOPRECORD.EQUSTATUSID
     *
     * @param equstatusid the value for PRD_CELLTASKSTOPRECORD.EQUSTATUSID
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public void setEqustatusid(String equstatusid) {
        this.equstatusid = equstatusid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_CELLTASKSTOPRECORD.STOPCLASS
     *
     * @return the value of PRD_CELLTASKSTOPRECORD.STOPCLASS
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public Short getStopclass() {
        return stopclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_CELLTASKSTOPRECORD.STOPCLASS
     *
     * @param stopclass the value for PRD_CELLTASKSTOPRECORD.STOPCLASS
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public void setStopclass(Short stopclass) {
        this.stopclass = stopclass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_CELLTASKSTOPRECORD.STOPTYPE
     *
     * @return the value of PRD_CELLTASKSTOPRECORD.STOPTYPE
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public String getStoptype() {
        return stoptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_CELLTASKSTOPRECORD.STOPTYPE
     *
     * @param stoptype the value for PRD_CELLTASKSTOPRECORD.STOPTYPE
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public void setStoptype(String stoptype) {
        this.stoptype = stoptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_CELLTASKSTOPRECORD.STOPREASON
     *
     * @return the value of PRD_CELLTASKSTOPRECORD.STOPREASON
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public String getStopreason() {
        return stopreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_CELLTASKSTOPRECORD.STOPREASON
     *
     * @param stopreason the value for PRD_CELLTASKSTOPRECORD.STOPREASON
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public void setStopreason(String stopreason) {
        this.stopreason = stopreason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_CELLTASKSTOPRECORD.STOPEQUCODE
     *
     * @return the value of PRD_CELLTASKSTOPRECORD.STOPEQUCODE
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public String getStopequcode() {
        return stopequcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_CELLTASKSTOPRECORD.STOPEQUCODE
     *
     * @param stopequcode the value for PRD_CELLTASKSTOPRECORD.STOPEQUCODE
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public void setStopequcode(String stopequcode) {
        this.stopequcode = stopequcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_CELLTASKSTOPRECORD.STOPEQUPART
     *
     * @return the value of PRD_CELLTASKSTOPRECORD.STOPEQUPART
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public String getStopequpart() {
        return stopequpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_CELLTASKSTOPRECORD.STOPEQUPART
     *
     * @param stopequpart the value for PRD_CELLTASKSTOPRECORD.STOPEQUPART
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public void setStopequpart(String stopequpart) {
        this.stopequpart = stopequpart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_CELLTASKSTOPRECORD.AUTHOR
     *
     * @return the value of PRD_CELLTASKSTOPRECORD.AUTHOR
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public String getAuthor() {
        return author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_CELLTASKSTOPRECORD.AUTHOR
     *
     * @param author the value for PRD_CELLTASKSTOPRECORD.AUTHOR
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public void setAuthor(String author) {
        this.author = author;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_CELLTASKSTOPRECORD.APPROVALDATE
     *
     * @return the value of PRD_CELLTASKSTOPRECORD.APPROVALDATE
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public Date getApprovaldate() {
        return approvaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_CELLTASKSTOPRECORD.APPROVALDATE
     *
     * @param approvaldate the value for PRD_CELLTASKSTOPRECORD.APPROVALDATE
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public void setApprovaldate(Date approvaldate) {
        this.approvaldate = approvaldate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_CELLTASKSTOPRECORD.STOPDESC
     *
     * @return the value of PRD_CELLTASKSTOPRECORD.STOPDESC
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public String getStopdesc() {
        return stopdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_CELLTASKSTOPRECORD.STOPDESC
     *
     * @param stopdesc the value for PRD_CELLTASKSTOPRECORD.STOPDESC
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public void setStopdesc(String stopdesc) {
        this.stopdesc = stopdesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_CELLTASKSTOPRECORD.ISPUBED
     *
     * @return the value of PRD_CELLTASKSTOPRECORD.ISPUBED
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public Long getIspubed() {
        return ispubed;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_CELLTASKSTOPRECORD.ISPUBED
     *
     * @param ispubed the value for PRD_CELLTASKSTOPRECORD.ISPUBED
     *
     * @mbg.generated Wed Jan 17 18:17:49 GMT+08:00 2024
     */
    public void setIspubed(Long ispubed) {
        this.ispubed = ispubed;
    }
}