package com.example.repository.model;

import java.util.Date;

public class PrdTaskCp {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.equipment_id
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String equipmentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.task_id
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.batch_id
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String batchId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.brand_id
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.task_start_time
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private Date taskStartTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.source
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.destination
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String destination;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.load_type
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String loadType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.path_code
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String pathCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.tank
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String tank;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp5
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp6
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp6;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.silo
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String silo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp7
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp7;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp8
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp8;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp9
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp9;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp10
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp10;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp11
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp11;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp12
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp12;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp13
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp13;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp14
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp14;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp15
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp15;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp16
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp16;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp17
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp17;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp18
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp18;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp19
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp19;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp20
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp20;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp21
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp21;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp22
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp22;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp23
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp23;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp24
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp24;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp25
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp25;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp26
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp26;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp27
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp27;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp28
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp28;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp29
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp29;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp30
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp30;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp31
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp31;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRD_TASK_CP.cp32
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    private String cp32;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.equipment_id
     *
     * @return the value of PRD_TASK_CP.equipment_id
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getEquipmentId() {
        return equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.equipment_id
     *
     * @param equipmentId the value for PRD_TASK_CP.equipment_id
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setEquipmentId(String equipmentId) {
        this.equipmentId = equipmentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.task_id
     *
     * @return the value of PRD_TASK_CP.task_id
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.task_id
     *
     * @param taskId the value for PRD_TASK_CP.task_id
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setTaskId(String taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.batch_id
     *
     * @return the value of PRD_TASK_CP.batch_id
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getBatchId() {
        return batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.batch_id
     *
     * @param batchId the value for PRD_TASK_CP.batch_id
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setBatchId(String batchId) {
        this.batchId = batchId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.brand_id
     *
     * @return the value of PRD_TASK_CP.brand_id
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.brand_id
     *
     * @param brandId the value for PRD_TASK_CP.brand_id
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setBrandId(String brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.task_start_time
     *
     * @return the value of PRD_TASK_CP.task_start_time
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public Date getTaskStartTime() {
        return taskStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.task_start_time
     *
     * @param taskStartTime the value for PRD_TASK_CP.task_start_time
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setTaskStartTime(Date taskStartTime) {
        this.taskStartTime = taskStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.source
     *
     * @return the value of PRD_TASK_CP.source
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.source
     *
     * @param source the value for PRD_TASK_CP.source
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.destination
     *
     * @return the value of PRD_TASK_CP.destination
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getDestination() {
        return destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.destination
     *
     * @param destination the value for PRD_TASK_CP.destination
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setDestination(String destination) {
        this.destination = destination;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.load_type
     *
     * @return the value of PRD_TASK_CP.load_type
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getLoadType() {
        return loadType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.load_type
     *
     * @param loadType the value for PRD_TASK_CP.load_type
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setLoadType(String loadType) {
        this.loadType = loadType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.path_code
     *
     * @return the value of PRD_TASK_CP.path_code
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getPathCode() {
        return pathCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.path_code
     *
     * @param pathCode the value for PRD_TASK_CP.path_code
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setPathCode(String pathCode) {
        this.pathCode = pathCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.tank
     *
     * @return the value of PRD_TASK_CP.tank
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getTank() {
        return tank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.tank
     *
     * @param tank the value for PRD_TASK_CP.tank
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setTank(String tank) {
        this.tank = tank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp5
     *
     * @return the value of PRD_TASK_CP.cp5
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp5() {
        return cp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp5
     *
     * @param cp5 the value for PRD_TASK_CP.cp5
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp5(String cp5) {
        this.cp5 = cp5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp6
     *
     * @return the value of PRD_TASK_CP.cp6
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp6() {
        return cp6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp6
     *
     * @param cp6 the value for PRD_TASK_CP.cp6
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp6(String cp6) {
        this.cp6 = cp6;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.silo
     *
     * @return the value of PRD_TASK_CP.silo
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getSilo() {
        return silo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.silo
     *
     * @param silo the value for PRD_TASK_CP.silo
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setSilo(String silo) {
        this.silo = silo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp7
     *
     * @return the value of PRD_TASK_CP.cp7
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp7() {
        return cp7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp7
     *
     * @param cp7 the value for PRD_TASK_CP.cp7
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp7(String cp7) {
        this.cp7 = cp7;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp8
     *
     * @return the value of PRD_TASK_CP.cp8
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp8() {
        return cp8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp8
     *
     * @param cp8 the value for PRD_TASK_CP.cp8
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp8(String cp8) {
        this.cp8 = cp8;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp9
     *
     * @return the value of PRD_TASK_CP.cp9
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp9() {
        return cp9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp9
     *
     * @param cp9 the value for PRD_TASK_CP.cp9
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp9(String cp9) {
        this.cp9 = cp9;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp10
     *
     * @return the value of PRD_TASK_CP.cp10
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp10() {
        return cp10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp10
     *
     * @param cp10 the value for PRD_TASK_CP.cp10
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp10(String cp10) {
        this.cp10 = cp10;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp11
     *
     * @return the value of PRD_TASK_CP.cp11
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp11() {
        return cp11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp11
     *
     * @param cp11 the value for PRD_TASK_CP.cp11
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp11(String cp11) {
        this.cp11 = cp11;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp12
     *
     * @return the value of PRD_TASK_CP.cp12
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp12() {
        return cp12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp12
     *
     * @param cp12 the value for PRD_TASK_CP.cp12
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp12(String cp12) {
        this.cp12 = cp12;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp13
     *
     * @return the value of PRD_TASK_CP.cp13
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp13() {
        return cp13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp13
     *
     * @param cp13 the value for PRD_TASK_CP.cp13
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp13(String cp13) {
        this.cp13 = cp13;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp14
     *
     * @return the value of PRD_TASK_CP.cp14
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp14() {
        return cp14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp14
     *
     * @param cp14 the value for PRD_TASK_CP.cp14
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp14(String cp14) {
        this.cp14 = cp14;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp15
     *
     * @return the value of PRD_TASK_CP.cp15
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp15() {
        return cp15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp15
     *
     * @param cp15 the value for PRD_TASK_CP.cp15
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp15(String cp15) {
        this.cp15 = cp15;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp16
     *
     * @return the value of PRD_TASK_CP.cp16
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp16() {
        return cp16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp16
     *
     * @param cp16 the value for PRD_TASK_CP.cp16
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp16(String cp16) {
        this.cp16 = cp16;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp17
     *
     * @return the value of PRD_TASK_CP.cp17
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp17() {
        return cp17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp17
     *
     * @param cp17 the value for PRD_TASK_CP.cp17
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp17(String cp17) {
        this.cp17 = cp17;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp18
     *
     * @return the value of PRD_TASK_CP.cp18
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp18() {
        return cp18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp18
     *
     * @param cp18 the value for PRD_TASK_CP.cp18
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp18(String cp18) {
        this.cp18 = cp18;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp19
     *
     * @return the value of PRD_TASK_CP.cp19
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp19() {
        return cp19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp19
     *
     * @param cp19 the value for PRD_TASK_CP.cp19
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp19(String cp19) {
        this.cp19 = cp19;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp20
     *
     * @return the value of PRD_TASK_CP.cp20
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp20() {
        return cp20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp20
     *
     * @param cp20 the value for PRD_TASK_CP.cp20
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp20(String cp20) {
        this.cp20 = cp20;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp21
     *
     * @return the value of PRD_TASK_CP.cp21
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp21() {
        return cp21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp21
     *
     * @param cp21 the value for PRD_TASK_CP.cp21
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp21(String cp21) {
        this.cp21 = cp21;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp22
     *
     * @return the value of PRD_TASK_CP.cp22
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp22() {
        return cp22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp22
     *
     * @param cp22 the value for PRD_TASK_CP.cp22
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp22(String cp22) {
        this.cp22 = cp22;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp23
     *
     * @return the value of PRD_TASK_CP.cp23
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp23() {
        return cp23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp23
     *
     * @param cp23 the value for PRD_TASK_CP.cp23
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp23(String cp23) {
        this.cp23 = cp23;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp24
     *
     * @return the value of PRD_TASK_CP.cp24
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp24() {
        return cp24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp24
     *
     * @param cp24 the value for PRD_TASK_CP.cp24
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp24(String cp24) {
        this.cp24 = cp24;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp25
     *
     * @return the value of PRD_TASK_CP.cp25
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp25() {
        return cp25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp25
     *
     * @param cp25 the value for PRD_TASK_CP.cp25
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp25(String cp25) {
        this.cp25 = cp25;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp26
     *
     * @return the value of PRD_TASK_CP.cp26
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp26() {
        return cp26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp26
     *
     * @param cp26 the value for PRD_TASK_CP.cp26
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp26(String cp26) {
        this.cp26 = cp26;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp27
     *
     * @return the value of PRD_TASK_CP.cp27
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp27() {
        return cp27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp27
     *
     * @param cp27 the value for PRD_TASK_CP.cp27
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp27(String cp27) {
        this.cp27 = cp27;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp28
     *
     * @return the value of PRD_TASK_CP.cp28
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp28() {
        return cp28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp28
     *
     * @param cp28 the value for PRD_TASK_CP.cp28
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp28(String cp28) {
        this.cp28 = cp28;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp29
     *
     * @return the value of PRD_TASK_CP.cp29
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp29() {
        return cp29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp29
     *
     * @param cp29 the value for PRD_TASK_CP.cp29
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp29(String cp29) {
        this.cp29 = cp29;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp30
     *
     * @return the value of PRD_TASK_CP.cp30
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp30() {
        return cp30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp30
     *
     * @param cp30 the value for PRD_TASK_CP.cp30
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp30(String cp30) {
        this.cp30 = cp30;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp31
     *
     * @return the value of PRD_TASK_CP.cp31
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp31() {
        return cp31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp31
     *
     * @param cp31 the value for PRD_TASK_CP.cp31
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp31(String cp31) {
        this.cp31 = cp31;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRD_TASK_CP.cp32
     *
     * @return the value of PRD_TASK_CP.cp32
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public String getCp32() {
        return cp32;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRD_TASK_CP.cp32
     *
     * @param cp32 the value for PRD_TASK_CP.cp32
     *
     * @mbg.generated Wed Oct 25 14:13:19 GMT+08:00 2023
     */
    public void setCp32(String cp32) {
        this.cp32 = cp32;
    }
}