package com.example.repository.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SiloinfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    public SiloinfoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBatchIdIsNull() {
            addCriterion("batch_id is null");
            return (Criteria) this;
        }

        public Criteria andBatchIdIsNotNull() {
            addCriterion("batch_id is not null");
            return (Criteria) this;
        }

        public Criteria andBatchIdEqualTo(String value) {
            addCriterion("batch_id =", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotEqualTo(String value) {
            addCriterion("batch_id <>", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdGreaterThan(String value) {
            addCriterion("batch_id >", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdGreaterThanOrEqualTo(String value) {
            addCriterion("batch_id >=", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLessThan(String value) {
            addCriterion("batch_id <", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLessThanOrEqualTo(String value) {
            addCriterion("batch_id <=", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdLike(String value) {
            addCriterion("batch_id like", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotLike(String value) {
            addCriterion("batch_id not like", value, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdIn(List<String> values) {
            addCriterion("batch_id in", values, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotIn(List<String> values) {
            addCriterion("batch_id not in", values, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdBetween(String value1, String value2) {
            addCriterion("batch_id between", value1, value2, "batchId");
            return (Criteria) this;
        }

        public Criteria andBatchIdNotBetween(String value1, String value2) {
            addCriterion("batch_id not between", value1, value2, "batchId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNull() {
            addCriterion("task_id is null");
            return (Criteria) this;
        }

        public Criteria andTaskIdIsNotNull() {
            addCriterion("task_id is not null");
            return (Criteria) this;
        }

        public Criteria andTaskIdEqualTo(String value) {
            addCriterion("task_id =", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotEqualTo(String value) {
            addCriterion("task_id <>", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThan(String value) {
            addCriterion("task_id >", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdGreaterThanOrEqualTo(String value) {
            addCriterion("task_id >=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThan(String value) {
            addCriterion("task_id <", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLessThanOrEqualTo(String value) {
            addCriterion("task_id <=", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdLike(String value) {
            addCriterion("task_id like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotLike(String value) {
            addCriterion("task_id not like", value, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdIn(List<String> values) {
            addCriterion("task_id in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotIn(List<String> values) {
            addCriterion("task_id not in", values, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdBetween(String value1, String value2) {
            addCriterion("task_id between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andTaskIdNotBetween(String value1, String value2) {
            addCriterion("task_id not between", value1, value2, "taskId");
            return (Criteria) this;
        }

        public Criteria andInOrOutIsNull() {
            addCriterion("in_or_out is null");
            return (Criteria) this;
        }

        public Criteria andInOrOutIsNotNull() {
            addCriterion("in_or_out is not null");
            return (Criteria) this;
        }

        public Criteria andInOrOutEqualTo(Integer value) {
            addCriterion("in_or_out =", value, "inOrOut");
            return (Criteria) this;
        }

        public Criteria andInOrOutNotEqualTo(Integer value) {
            addCriterion("in_or_out <>", value, "inOrOut");
            return (Criteria) this;
        }

        public Criteria andInOrOutGreaterThan(Integer value) {
            addCriterion("in_or_out >", value, "inOrOut");
            return (Criteria) this;
        }

        public Criteria andInOrOutGreaterThanOrEqualTo(Integer value) {
            addCriterion("in_or_out >=", value, "inOrOut");
            return (Criteria) this;
        }

        public Criteria andInOrOutLessThan(Integer value) {
            addCriterion("in_or_out <", value, "inOrOut");
            return (Criteria) this;
        }

        public Criteria andInOrOutLessThanOrEqualTo(Integer value) {
            addCriterion("in_or_out <=", value, "inOrOut");
            return (Criteria) this;
        }

        public Criteria andInOrOutIn(List<Integer> values) {
            addCriterion("in_or_out in", values, "inOrOut");
            return (Criteria) this;
        }

        public Criteria andInOrOutNotIn(List<Integer> values) {
            addCriterion("in_or_out not in", values, "inOrOut");
            return (Criteria) this;
        }

        public Criteria andInOrOutBetween(Integer value1, Integer value2) {
            addCriterion("in_or_out between", value1, value2, "inOrOut");
            return (Criteria) this;
        }

        public Criteria andInOrOutNotBetween(Integer value1, Integer value2) {
            addCriterion("in_or_out not between", value1, value2, "inOrOut");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNull() {
            addCriterion("brand_id is null");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNotNull() {
            addCriterion("brand_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrandIdEqualTo(String value) {
            addCriterion("brand_id =", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotEqualTo(String value) {
            addCriterion("brand_id <>", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThan(String value) {
            addCriterion("brand_id >", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThanOrEqualTo(String value) {
            addCriterion("brand_id >=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThan(String value) {
            addCriterion("brand_id <", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThanOrEqualTo(String value) {
            addCriterion("brand_id <=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLike(String value) {
            addCriterion("brand_id like", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotLike(String value) {
            addCriterion("brand_id not like", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdIn(List<String> values) {
            addCriterion("brand_id in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotIn(List<String> values) {
            addCriterion("brand_id not in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdBetween(String value1, String value2) {
            addCriterion("brand_id between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotBetween(String value1, String value2) {
            addCriterion("brand_id not between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandNameIsNull() {
            addCriterion("brand_name is null");
            return (Criteria) this;
        }

        public Criteria andBrandNameIsNotNull() {
            addCriterion("brand_name is not null");
            return (Criteria) this;
        }

        public Criteria andBrandNameEqualTo(String value) {
            addCriterion("brand_name =", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotEqualTo(String value) {
            addCriterion("brand_name <>", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameGreaterThan(String value) {
            addCriterion("brand_name >", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameGreaterThanOrEqualTo(String value) {
            addCriterion("brand_name >=", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLessThan(String value) {
            addCriterion("brand_name <", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLessThanOrEqualTo(String value) {
            addCriterion("brand_name <=", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLike(String value) {
            addCriterion("brand_name like", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotLike(String value) {
            addCriterion("brand_name not like", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameIn(List<String> values) {
            addCriterion("brand_name in", values, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotIn(List<String> values) {
            addCriterion("brand_name not in", values, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameBetween(String value1, String value2) {
            addCriterion("brand_name between", value1, value2, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotBetween(String value1, String value2) {
            addCriterion("brand_name not between", value1, value2, "brandName");
            return (Criteria) this;
        }

        public Criteria andModNoIsNull() {
            addCriterion("mod_no is null");
            return (Criteria) this;
        }

        public Criteria andModNoIsNotNull() {
            addCriterion("mod_no is not null");
            return (Criteria) this;
        }

        public Criteria andModNoEqualTo(String value) {
            addCriterion("mod_no =", value, "modNo");
            return (Criteria) this;
        }

        public Criteria andModNoNotEqualTo(String value) {
            addCriterion("mod_no <>", value, "modNo");
            return (Criteria) this;
        }

        public Criteria andModNoGreaterThan(String value) {
            addCriterion("mod_no >", value, "modNo");
            return (Criteria) this;
        }

        public Criteria andModNoGreaterThanOrEqualTo(String value) {
            addCriterion("mod_no >=", value, "modNo");
            return (Criteria) this;
        }

        public Criteria andModNoLessThan(String value) {
            addCriterion("mod_no <", value, "modNo");
            return (Criteria) this;
        }

        public Criteria andModNoLessThanOrEqualTo(String value) {
            addCriterion("mod_no <=", value, "modNo");
            return (Criteria) this;
        }

        public Criteria andModNoLike(String value) {
            addCriterion("mod_no like", value, "modNo");
            return (Criteria) this;
        }

        public Criteria andModNoNotLike(String value) {
            addCriterion("mod_no not like", value, "modNo");
            return (Criteria) this;
        }

        public Criteria andModNoIn(List<String> values) {
            addCriterion("mod_no in", values, "modNo");
            return (Criteria) this;
        }

        public Criteria andModNoNotIn(List<String> values) {
            addCriterion("mod_no not in", values, "modNo");
            return (Criteria) this;
        }

        public Criteria andModNoBetween(String value1, String value2) {
            addCriterion("mod_no between", value1, value2, "modNo");
            return (Criteria) this;
        }

        public Criteria andModNoNotBetween(String value1, String value2) {
            addCriterion("mod_no not between", value1, value2, "modNo");
            return (Criteria) this;
        }

        public Criteria andModNmIsNull() {
            addCriterion("mod_nm is null");
            return (Criteria) this;
        }

        public Criteria andModNmIsNotNull() {
            addCriterion("mod_nm is not null");
            return (Criteria) this;
        }

        public Criteria andModNmEqualTo(String value) {
            addCriterion("mod_nm =", value, "modNm");
            return (Criteria) this;
        }

        public Criteria andModNmNotEqualTo(String value) {
            addCriterion("mod_nm <>", value, "modNm");
            return (Criteria) this;
        }

        public Criteria andModNmGreaterThan(String value) {
            addCriterion("mod_nm >", value, "modNm");
            return (Criteria) this;
        }

        public Criteria andModNmGreaterThanOrEqualTo(String value) {
            addCriterion("mod_nm >=", value, "modNm");
            return (Criteria) this;
        }

        public Criteria andModNmLessThan(String value) {
            addCriterion("mod_nm <", value, "modNm");
            return (Criteria) this;
        }

        public Criteria andModNmLessThanOrEqualTo(String value) {
            addCriterion("mod_nm <=", value, "modNm");
            return (Criteria) this;
        }

        public Criteria andModNmLike(String value) {
            addCriterion("mod_nm like", value, "modNm");
            return (Criteria) this;
        }

        public Criteria andModNmNotLike(String value) {
            addCriterion("mod_nm not like", value, "modNm");
            return (Criteria) this;
        }

        public Criteria andModNmIn(List<String> values) {
            addCriterion("mod_nm in", values, "modNm");
            return (Criteria) this;
        }

        public Criteria andModNmNotIn(List<String> values) {
            addCriterion("mod_nm not in", values, "modNm");
            return (Criteria) this;
        }

        public Criteria andModNmBetween(String value1, String value2) {
            addCriterion("mod_nm between", value1, value2, "modNm");
            return (Criteria) this;
        }

        public Criteria andModNmNotBetween(String value1, String value2) {
            addCriterion("mod_nm not between", value1, value2, "modNm");
            return (Criteria) this;
        }

        public Criteria andPathNoIsNull() {
            addCriterion("path_no is null");
            return (Criteria) this;
        }

        public Criteria andPathNoIsNotNull() {
            addCriterion("path_no is not null");
            return (Criteria) this;
        }

        public Criteria andPathNoEqualTo(String value) {
            addCriterion("path_no =", value, "pathNo");
            return (Criteria) this;
        }

        public Criteria andPathNoNotEqualTo(String value) {
            addCriterion("path_no <>", value, "pathNo");
            return (Criteria) this;
        }

        public Criteria andPathNoGreaterThan(String value) {
            addCriterion("path_no >", value, "pathNo");
            return (Criteria) this;
        }

        public Criteria andPathNoGreaterThanOrEqualTo(String value) {
            addCriterion("path_no >=", value, "pathNo");
            return (Criteria) this;
        }

        public Criteria andPathNoLessThan(String value) {
            addCriterion("path_no <", value, "pathNo");
            return (Criteria) this;
        }

        public Criteria andPathNoLessThanOrEqualTo(String value) {
            addCriterion("path_no <=", value, "pathNo");
            return (Criteria) this;
        }

        public Criteria andPathNoLike(String value) {
            addCriterion("path_no like", value, "pathNo");
            return (Criteria) this;
        }

        public Criteria andPathNoNotLike(String value) {
            addCriterion("path_no not like", value, "pathNo");
            return (Criteria) this;
        }

        public Criteria andPathNoIn(List<String> values) {
            addCriterion("path_no in", values, "pathNo");
            return (Criteria) this;
        }

        public Criteria andPathNoNotIn(List<String> values) {
            addCriterion("path_no not in", values, "pathNo");
            return (Criteria) this;
        }

        public Criteria andPathNoBetween(String value1, String value2) {
            addCriterion("path_no between", value1, value2, "pathNo");
            return (Criteria) this;
        }

        public Criteria andPathNoNotBetween(String value1, String value2) {
            addCriterion("path_no not between", value1, value2, "pathNo");
            return (Criteria) this;
        }

        public Criteria andPathNmIsNull() {
            addCriterion("path_nm is null");
            return (Criteria) this;
        }

        public Criteria andPathNmIsNotNull() {
            addCriterion("path_nm is not null");
            return (Criteria) this;
        }

        public Criteria andPathNmEqualTo(String value) {
            addCriterion("path_nm =", value, "pathNm");
            return (Criteria) this;
        }

        public Criteria andPathNmNotEqualTo(String value) {
            addCriterion("path_nm <>", value, "pathNm");
            return (Criteria) this;
        }

        public Criteria andPathNmGreaterThan(String value) {
            addCriterion("path_nm >", value, "pathNm");
            return (Criteria) this;
        }

        public Criteria andPathNmGreaterThanOrEqualTo(String value) {
            addCriterion("path_nm >=", value, "pathNm");
            return (Criteria) this;
        }

        public Criteria andPathNmLessThan(String value) {
            addCriterion("path_nm <", value, "pathNm");
            return (Criteria) this;
        }

        public Criteria andPathNmLessThanOrEqualTo(String value) {
            addCriterion("path_nm <=", value, "pathNm");
            return (Criteria) this;
        }

        public Criteria andPathNmLike(String value) {
            addCriterion("path_nm like", value, "pathNm");
            return (Criteria) this;
        }

        public Criteria andPathNmNotLike(String value) {
            addCriterion("path_nm not like", value, "pathNm");
            return (Criteria) this;
        }

        public Criteria andPathNmIn(List<String> values) {
            addCriterion("path_nm in", values, "pathNm");
            return (Criteria) this;
        }

        public Criteria andPathNmNotIn(List<String> values) {
            addCriterion("path_nm not in", values, "pathNm");
            return (Criteria) this;
        }

        public Criteria andPathNmBetween(String value1, String value2) {
            addCriterion("path_nm between", value1, value2, "pathNm");
            return (Criteria) this;
        }

        public Criteria andPathNmNotBetween(String value1, String value2) {
            addCriterion("path_nm not between", value1, value2, "pathNm");
            return (Criteria) this;
        }

        public Criteria andCrVersionIsNull() {
            addCriterion("cr_version is null");
            return (Criteria) this;
        }

        public Criteria andCrVersionIsNotNull() {
            addCriterion("cr_version is not null");
            return (Criteria) this;
        }

        public Criteria andCrVersionEqualTo(String value) {
            addCriterion("cr_version =", value, "crVersion");
            return (Criteria) this;
        }

        public Criteria andCrVersionNotEqualTo(String value) {
            addCriterion("cr_version <>", value, "crVersion");
            return (Criteria) this;
        }

        public Criteria andCrVersionGreaterThan(String value) {
            addCriterion("cr_version >", value, "crVersion");
            return (Criteria) this;
        }

        public Criteria andCrVersionGreaterThanOrEqualTo(String value) {
            addCriterion("cr_version >=", value, "crVersion");
            return (Criteria) this;
        }

        public Criteria andCrVersionLessThan(String value) {
            addCriterion("cr_version <", value, "crVersion");
            return (Criteria) this;
        }

        public Criteria andCrVersionLessThanOrEqualTo(String value) {
            addCriterion("cr_version <=", value, "crVersion");
            return (Criteria) this;
        }

        public Criteria andCrVersionLike(String value) {
            addCriterion("cr_version like", value, "crVersion");
            return (Criteria) this;
        }

        public Criteria andCrVersionNotLike(String value) {
            addCriterion("cr_version not like", value, "crVersion");
            return (Criteria) this;
        }

        public Criteria andCrVersionIn(List<String> values) {
            addCriterion("cr_version in", values, "crVersion");
            return (Criteria) this;
        }

        public Criteria andCrVersionNotIn(List<String> values) {
            addCriterion("cr_version not in", values, "crVersion");
            return (Criteria) this;
        }

        public Criteria andCrVersionBetween(String value1, String value2) {
            addCriterion("cr_version between", value1, value2, "crVersion");
            return (Criteria) this;
        }

        public Criteria andCrVersionNotBetween(String value1, String value2) {
            addCriterion("cr_version not between", value1, value2, "crVersion");
            return (Criteria) this;
        }

        public Criteria andBatchWeightIsNull() {
            addCriterion("batch_weight is null");
            return (Criteria) this;
        }

        public Criteria andBatchWeightIsNotNull() {
            addCriterion("batch_weight is not null");
            return (Criteria) this;
        }

        public Criteria andBatchWeightEqualTo(Float value) {
            addCriterion("batch_weight =", value, "batchWeight");
            return (Criteria) this;
        }

        public Criteria andBatchWeightNotEqualTo(Float value) {
            addCriterion("batch_weight <>", value, "batchWeight");
            return (Criteria) this;
        }

        public Criteria andBatchWeightGreaterThan(Float value) {
            addCriterion("batch_weight >", value, "batchWeight");
            return (Criteria) this;
        }

        public Criteria andBatchWeightGreaterThanOrEqualTo(Float value) {
            addCriterion("batch_weight >=", value, "batchWeight");
            return (Criteria) this;
        }

        public Criteria andBatchWeightLessThan(Float value) {
            addCriterion("batch_weight <", value, "batchWeight");
            return (Criteria) this;
        }

        public Criteria andBatchWeightLessThanOrEqualTo(Float value) {
            addCriterion("batch_weight <=", value, "batchWeight");
            return (Criteria) this;
        }

        public Criteria andBatchWeightIn(List<Float> values) {
            addCriterion("batch_weight in", values, "batchWeight");
            return (Criteria) this;
        }

        public Criteria andBatchWeightNotIn(List<Float> values) {
            addCriterion("batch_weight not in", values, "batchWeight");
            return (Criteria) this;
        }

        public Criteria andBatchWeightBetween(Float value1, Float value2) {
            addCriterion("batch_weight between", value1, value2, "batchWeight");
            return (Criteria) this;
        }

        public Criteria andBatchWeightNotBetween(Float value1, Float value2) {
            addCriterion("batch_weight not between", value1, value2, "batchWeight");
            return (Criteria) this;
        }

        public Criteria andAmountOfCategoriesIsNull() {
            addCriterion("amount_of_categories is null");
            return (Criteria) this;
        }

        public Criteria andAmountOfCategoriesIsNotNull() {
            addCriterion("amount_of_categories is not null");
            return (Criteria) this;
        }

        public Criteria andAmountOfCategoriesEqualTo(Float value) {
            addCriterion("amount_of_categories =", value, "amountOfCategories");
            return (Criteria) this;
        }

        public Criteria andAmountOfCategoriesNotEqualTo(Float value) {
            addCriterion("amount_of_categories <>", value, "amountOfCategories");
            return (Criteria) this;
        }

        public Criteria andAmountOfCategoriesGreaterThan(Float value) {
            addCriterion("amount_of_categories >", value, "amountOfCategories");
            return (Criteria) this;
        }

        public Criteria andAmountOfCategoriesGreaterThanOrEqualTo(Float value) {
            addCriterion("amount_of_categories >=", value, "amountOfCategories");
            return (Criteria) this;
        }

        public Criteria andAmountOfCategoriesLessThan(Float value) {
            addCriterion("amount_of_categories <", value, "amountOfCategories");
            return (Criteria) this;
        }

        public Criteria andAmountOfCategoriesLessThanOrEqualTo(Float value) {
            addCriterion("amount_of_categories <=", value, "amountOfCategories");
            return (Criteria) this;
        }

        public Criteria andAmountOfCategoriesIn(List<Float> values) {
            addCriterion("amount_of_categories in", values, "amountOfCategories");
            return (Criteria) this;
        }

        public Criteria andAmountOfCategoriesNotIn(List<Float> values) {
            addCriterion("amount_of_categories not in", values, "amountOfCategories");
            return (Criteria) this;
        }

        public Criteria andAmountOfCategoriesBetween(Float value1, Float value2) {
            addCriterion("amount_of_categories between", value1, value2, "amountOfCategories");
            return (Criteria) this;
        }

        public Criteria andAmountOfCategoriesNotBetween(Float value1, Float value2) {
            addCriterion("amount_of_categories not between", value1, value2, "amountOfCategories");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeIsNull() {
            addCriterion("plan_start_time is null");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeIsNotNull() {
            addCriterion("plan_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeEqualTo(Date value) {
            addCriterion("plan_start_time =", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeNotEqualTo(Date value) {
            addCriterion("plan_start_time <>", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeGreaterThan(Date value) {
            addCriterion("plan_start_time >", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("plan_start_time >=", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeLessThan(Date value) {
            addCriterion("plan_start_time <", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("plan_start_time <=", value, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeIn(List<Date> values) {
            addCriterion("plan_start_time in", values, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeNotIn(List<Date> values) {
            addCriterion("plan_start_time not in", values, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeBetween(Date value1, Date value2) {
            addCriterion("plan_start_time between", value1, value2, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("plan_start_time not between", value1, value2, "planStartTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeIsNull() {
            addCriterion("plan_end_time is null");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeIsNotNull() {
            addCriterion("plan_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeEqualTo(Date value) {
            addCriterion("plan_end_time =", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeNotEqualTo(Date value) {
            addCriterion("plan_end_time <>", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeGreaterThan(Date value) {
            addCriterion("plan_end_time >", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("plan_end_time >=", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeLessThan(Date value) {
            addCriterion("plan_end_time <", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("plan_end_time <=", value, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeIn(List<Date> values) {
            addCriterion("plan_end_time in", values, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeNotIn(List<Date> values) {
            addCriterion("plan_end_time not in", values, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeBetween(Date value1, Date value2) {
            addCriterion("plan_end_time between", value1, value2, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andPlanEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("plan_end_time not between", value1, value2, "planEndTime");
            return (Criteria) this;
        }

        public Criteria andSequenceNmIsNull() {
            addCriterion("sequence_nm is null");
            return (Criteria) this;
        }

        public Criteria andSequenceNmIsNotNull() {
            addCriterion("sequence_nm is not null");
            return (Criteria) this;
        }

        public Criteria andSequenceNmEqualTo(Float value) {
            addCriterion("sequence_nm =", value, "sequenceNm");
            return (Criteria) this;
        }

        public Criteria andSequenceNmNotEqualTo(Float value) {
            addCriterion("sequence_nm <>", value, "sequenceNm");
            return (Criteria) this;
        }

        public Criteria andSequenceNmGreaterThan(Float value) {
            addCriterion("sequence_nm >", value, "sequenceNm");
            return (Criteria) this;
        }

        public Criteria andSequenceNmGreaterThanOrEqualTo(Float value) {
            addCriterion("sequence_nm >=", value, "sequenceNm");
            return (Criteria) this;
        }

        public Criteria andSequenceNmLessThan(Float value) {
            addCriterion("sequence_nm <", value, "sequenceNm");
            return (Criteria) this;
        }

        public Criteria andSequenceNmLessThanOrEqualTo(Float value) {
            addCriterion("sequence_nm <=", value, "sequenceNm");
            return (Criteria) this;
        }

        public Criteria andSequenceNmIn(List<Float> values) {
            addCriterion("sequence_nm in", values, "sequenceNm");
            return (Criteria) this;
        }

        public Criteria andSequenceNmNotIn(List<Float> values) {
            addCriterion("sequence_nm not in", values, "sequenceNm");
            return (Criteria) this;
        }

        public Criteria andSequenceNmBetween(Float value1, Float value2) {
            addCriterion("sequence_nm between", value1, value2, "sequenceNm");
            return (Criteria) this;
        }

        public Criteria andSequenceNmNotBetween(Float value1, Float value2) {
            addCriterion("sequence_nm not between", value1, value2, "sequenceNm");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Float value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Float value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Float value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Float value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Float value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Float value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Float> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Float> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Float value1, Float value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Float value1, Float value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNull() {
            addCriterion("class_id is null");
            return (Criteria) this;
        }

        public Criteria andClassIdIsNotNull() {
            addCriterion("class_id is not null");
            return (Criteria) this;
        }

        public Criteria andClassIdEqualTo(Float value) {
            addCriterion("class_id =", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotEqualTo(Float value) {
            addCriterion("class_id <>", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThan(Float value) {
            addCriterion("class_id >", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdGreaterThanOrEqualTo(Float value) {
            addCriterion("class_id >=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThan(Float value) {
            addCriterion("class_id <", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdLessThanOrEqualTo(Float value) {
            addCriterion("class_id <=", value, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdIn(List<Float> values) {
            addCriterion("class_id in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotIn(List<Float> values) {
            addCriterion("class_id not in", values, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdBetween(Float value1, Float value2) {
            addCriterion("class_id between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassIdNotBetween(Float value1, Float value2) {
            addCriterion("class_id not between", value1, value2, "classId");
            return (Criteria) this;
        }

        public Criteria andClassTypeIsNull() {
            addCriterion("class_type is null");
            return (Criteria) this;
        }

        public Criteria andClassTypeIsNotNull() {
            addCriterion("class_type is not null");
            return (Criteria) this;
        }

        public Criteria andClassTypeEqualTo(Float value) {
            addCriterion("class_type =", value, "classType");
            return (Criteria) this;
        }

        public Criteria andClassTypeNotEqualTo(Float value) {
            addCriterion("class_type <>", value, "classType");
            return (Criteria) this;
        }

        public Criteria andClassTypeGreaterThan(Float value) {
            addCriterion("class_type >", value, "classType");
            return (Criteria) this;
        }

        public Criteria andClassTypeGreaterThanOrEqualTo(Float value) {
            addCriterion("class_type >=", value, "classType");
            return (Criteria) this;
        }

        public Criteria andClassTypeLessThan(Float value) {
            addCriterion("class_type <", value, "classType");
            return (Criteria) this;
        }

        public Criteria andClassTypeLessThanOrEqualTo(Float value) {
            addCriterion("class_type <=", value, "classType");
            return (Criteria) this;
        }

        public Criteria andClassTypeIn(List<Float> values) {
            addCriterion("class_type in", values, "classType");
            return (Criteria) this;
        }

        public Criteria andClassTypeNotIn(List<Float> values) {
            addCriterion("class_type not in", values, "classType");
            return (Criteria) this;
        }

        public Criteria andClassTypeBetween(Float value1, Float value2) {
            addCriterion("class_type between", value1, value2, "classType");
            return (Criteria) this;
        }

        public Criteria andClassTypeNotBetween(Float value1, Float value2) {
            addCriterion("class_type not between", value1, value2, "classType");
            return (Criteria) this;
        }

        public Criteria andSiloIdIsNull() {
            addCriterion("silo_id is null");
            return (Criteria) this;
        }

        public Criteria andSiloIdIsNotNull() {
            addCriterion("silo_id is not null");
            return (Criteria) this;
        }

        public Criteria andSiloIdEqualTo(Float value) {
            addCriterion("silo_id =", value, "siloId");
            return (Criteria) this;
        }

        public Criteria andSiloIdNotEqualTo(Float value) {
            addCriterion("silo_id <>", value, "siloId");
            return (Criteria) this;
        }

        public Criteria andSiloIdGreaterThan(Float value) {
            addCriterion("silo_id >", value, "siloId");
            return (Criteria) this;
        }

        public Criteria andSiloIdGreaterThanOrEqualTo(Float value) {
            addCriterion("silo_id >=", value, "siloId");
            return (Criteria) this;
        }

        public Criteria andSiloIdLessThan(Float value) {
            addCriterion("silo_id <", value, "siloId");
            return (Criteria) this;
        }

        public Criteria andSiloIdLessThanOrEqualTo(Float value) {
            addCriterion("silo_id <=", value, "siloId");
            return (Criteria) this;
        }

        public Criteria andSiloIdIn(List<Float> values) {
            addCriterion("silo_id in", values, "siloId");
            return (Criteria) this;
        }

        public Criteria andSiloIdNotIn(List<Float> values) {
            addCriterion("silo_id not in", values, "siloId");
            return (Criteria) this;
        }

        public Criteria andSiloIdBetween(Float value1, Float value2) {
            addCriterion("silo_id between", value1, value2, "siloId");
            return (Criteria) this;
        }

        public Criteria andSiloIdNotBetween(Float value1, Float value2) {
            addCriterion("silo_id not between", value1, value2, "siloId");
            return (Criteria) this;
        }

        public Criteria andGroupNumIsNull() {
            addCriterion("group_num is null");
            return (Criteria) this;
        }

        public Criteria andGroupNumIsNotNull() {
            addCriterion("group_num is not null");
            return (Criteria) this;
        }

        public Criteria andGroupNumEqualTo(Integer value) {
            addCriterion("group_num =", value, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumNotEqualTo(Integer value) {
            addCriterion("group_num <>", value, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumGreaterThan(Integer value) {
            addCriterion("group_num >", value, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumGreaterThanOrEqualTo(Integer value) {
            addCriterion("group_num >=", value, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumLessThan(Integer value) {
            addCriterion("group_num <", value, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumLessThanOrEqualTo(Integer value) {
            addCriterion("group_num <=", value, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumIn(List<Integer> values) {
            addCriterion("group_num in", values, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumNotIn(List<Integer> values) {
            addCriterion("group_num not in", values, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumBetween(Integer value1, Integer value2) {
            addCriterion("group_num between", value1, value2, "groupNum");
            return (Criteria) this;
        }

        public Criteria andGroupNumNotBetween(Integer value1, Integer value2) {
            addCriterion("group_num not between", value1, value2, "groupNum");
            return (Criteria) this;
        }

        public Criteria andTypeOfLoadedIsNull() {
            addCriterion("type_of_loaded is null");
            return (Criteria) this;
        }

        public Criteria andTypeOfLoadedIsNotNull() {
            addCriterion("type_of_loaded is not null");
            return (Criteria) this;
        }

        public Criteria andTypeOfLoadedEqualTo(Float value) {
            addCriterion("type_of_loaded =", value, "typeOfLoaded");
            return (Criteria) this;
        }

        public Criteria andTypeOfLoadedNotEqualTo(Float value) {
            addCriterion("type_of_loaded <>", value, "typeOfLoaded");
            return (Criteria) this;
        }

        public Criteria andTypeOfLoadedGreaterThan(Float value) {
            addCriterion("type_of_loaded >", value, "typeOfLoaded");
            return (Criteria) this;
        }

        public Criteria andTypeOfLoadedGreaterThanOrEqualTo(Float value) {
            addCriterion("type_of_loaded >=", value, "typeOfLoaded");
            return (Criteria) this;
        }

        public Criteria andTypeOfLoadedLessThan(Float value) {
            addCriterion("type_of_loaded <", value, "typeOfLoaded");
            return (Criteria) this;
        }

        public Criteria andTypeOfLoadedLessThanOrEqualTo(Float value) {
            addCriterion("type_of_loaded <=", value, "typeOfLoaded");
            return (Criteria) this;
        }

        public Criteria andTypeOfLoadedIn(List<Float> values) {
            addCriterion("type_of_loaded in", values, "typeOfLoaded");
            return (Criteria) this;
        }

        public Criteria andTypeOfLoadedNotIn(List<Float> values) {
            addCriterion("type_of_loaded not in", values, "typeOfLoaded");
            return (Criteria) this;
        }

        public Criteria andTypeOfLoadedBetween(Float value1, Float value2) {
            addCriterion("type_of_loaded between", value1, value2, "typeOfLoaded");
            return (Criteria) this;
        }

        public Criteria andTypeOfLoadedNotBetween(Float value1, Float value2) {
            addCriterion("type_of_loaded not between", value1, value2, "typeOfLoaded");
            return (Criteria) this;
        }

        public Criteria andLoadedWeightIsNull() {
            addCriterion("loaded_weight is null");
            return (Criteria) this;
        }

        public Criteria andLoadedWeightIsNotNull() {
            addCriterion("loaded_weight is not null");
            return (Criteria) this;
        }

        public Criteria andLoadedWeightEqualTo(Float value) {
            addCriterion("loaded_weight =", value, "loadedWeight");
            return (Criteria) this;
        }

        public Criteria andLoadedWeightNotEqualTo(Float value) {
            addCriterion("loaded_weight <>", value, "loadedWeight");
            return (Criteria) this;
        }

        public Criteria andLoadedWeightGreaterThan(Float value) {
            addCriterion("loaded_weight >", value, "loadedWeight");
            return (Criteria) this;
        }

        public Criteria andLoadedWeightGreaterThanOrEqualTo(Float value) {
            addCriterion("loaded_weight >=", value, "loadedWeight");
            return (Criteria) this;
        }

        public Criteria andLoadedWeightLessThan(Float value) {
            addCriterion("loaded_weight <", value, "loadedWeight");
            return (Criteria) this;
        }

        public Criteria andLoadedWeightLessThanOrEqualTo(Float value) {
            addCriterion("loaded_weight <=", value, "loadedWeight");
            return (Criteria) this;
        }

        public Criteria andLoadedWeightIn(List<Float> values) {
            addCriterion("loaded_weight in", values, "loadedWeight");
            return (Criteria) this;
        }

        public Criteria andLoadedWeightNotIn(List<Float> values) {
            addCriterion("loaded_weight not in", values, "loadedWeight");
            return (Criteria) this;
        }

        public Criteria andLoadedWeightBetween(Float value1, Float value2) {
            addCriterion("loaded_weight between", value1, value2, "loadedWeight");
            return (Criteria) this;
        }

        public Criteria andLoadedWeightNotBetween(Float value1, Float value2) {
            addCriterion("loaded_weight not between", value1, value2, "loadedWeight");
            return (Criteria) this;
        }

        public Criteria andDryTobaccoWeightIsNull() {
            addCriterion("dry_tobacco_weight is null");
            return (Criteria) this;
        }

        public Criteria andDryTobaccoWeightIsNotNull() {
            addCriterion("dry_tobacco_weight is not null");
            return (Criteria) this;
        }

        public Criteria andDryTobaccoWeightEqualTo(Float value) {
            addCriterion("dry_tobacco_weight =", value, "dryTobaccoWeight");
            return (Criteria) this;
        }

        public Criteria andDryTobaccoWeightNotEqualTo(Float value) {
            addCriterion("dry_tobacco_weight <>", value, "dryTobaccoWeight");
            return (Criteria) this;
        }

        public Criteria andDryTobaccoWeightGreaterThan(Float value) {
            addCriterion("dry_tobacco_weight >", value, "dryTobaccoWeight");
            return (Criteria) this;
        }

        public Criteria andDryTobaccoWeightGreaterThanOrEqualTo(Float value) {
            addCriterion("dry_tobacco_weight >=", value, "dryTobaccoWeight");
            return (Criteria) this;
        }

        public Criteria andDryTobaccoWeightLessThan(Float value) {
            addCriterion("dry_tobacco_weight <", value, "dryTobaccoWeight");
            return (Criteria) this;
        }

        public Criteria andDryTobaccoWeightLessThanOrEqualTo(Float value) {
            addCriterion("dry_tobacco_weight <=", value, "dryTobaccoWeight");
            return (Criteria) this;
        }

        public Criteria andDryTobaccoWeightIn(List<Float> values) {
            addCriterion("dry_tobacco_weight in", values, "dryTobaccoWeight");
            return (Criteria) this;
        }

        public Criteria andDryTobaccoWeightNotIn(List<Float> values) {
            addCriterion("dry_tobacco_weight not in", values, "dryTobaccoWeight");
            return (Criteria) this;
        }

        public Criteria andDryTobaccoWeightBetween(Float value1, Float value2) {
            addCriterion("dry_tobacco_weight between", value1, value2, "dryTobaccoWeight");
            return (Criteria) this;
        }

        public Criteria andDryTobaccoWeightNotBetween(Float value1, Float value2) {
            addCriterion("dry_tobacco_weight not between", value1, value2, "dryTobaccoWeight");
            return (Criteria) this;
        }

        public Criteria andAvMoistureIsNull() {
            addCriterion("av_moisture is null");
            return (Criteria) this;
        }

        public Criteria andAvMoistureIsNotNull() {
            addCriterion("av_moisture is not null");
            return (Criteria) this;
        }

        public Criteria andAvMoistureEqualTo(Float value) {
            addCriterion("av_moisture =", value, "avMoisture");
            return (Criteria) this;
        }

        public Criteria andAvMoistureNotEqualTo(Float value) {
            addCriterion("av_moisture <>", value, "avMoisture");
            return (Criteria) this;
        }

        public Criteria andAvMoistureGreaterThan(Float value) {
            addCriterion("av_moisture >", value, "avMoisture");
            return (Criteria) this;
        }

        public Criteria andAvMoistureGreaterThanOrEqualTo(Float value) {
            addCriterion("av_moisture >=", value, "avMoisture");
            return (Criteria) this;
        }

        public Criteria andAvMoistureLessThan(Float value) {
            addCriterion("av_moisture <", value, "avMoisture");
            return (Criteria) this;
        }

        public Criteria andAvMoistureLessThanOrEqualTo(Float value) {
            addCriterion("av_moisture <=", value, "avMoisture");
            return (Criteria) this;
        }

        public Criteria andAvMoistureIn(List<Float> values) {
            addCriterion("av_moisture in", values, "avMoisture");
            return (Criteria) this;
        }

        public Criteria andAvMoistureNotIn(List<Float> values) {
            addCriterion("av_moisture not in", values, "avMoisture");
            return (Criteria) this;
        }

        public Criteria andAvMoistureBetween(Float value1, Float value2) {
            addCriterion("av_moisture between", value1, value2, "avMoisture");
            return (Criteria) this;
        }

        public Criteria andAvMoistureNotBetween(Float value1, Float value2) {
            addCriterion("av_moisture not between", value1, value2, "avMoisture");
            return (Criteria) this;
        }

        public Criteria andRemainWeightIsNull() {
            addCriterion("remain_weight is null");
            return (Criteria) this;
        }

        public Criteria andRemainWeightIsNotNull() {
            addCriterion("remain_weight is not null");
            return (Criteria) this;
        }

        public Criteria andRemainWeightEqualTo(Float value) {
            addCriterion("remain_weight =", value, "remainWeight");
            return (Criteria) this;
        }

        public Criteria andRemainWeightNotEqualTo(Float value) {
            addCriterion("remain_weight <>", value, "remainWeight");
            return (Criteria) this;
        }

        public Criteria andRemainWeightGreaterThan(Float value) {
            addCriterion("remain_weight >", value, "remainWeight");
            return (Criteria) this;
        }

        public Criteria andRemainWeightGreaterThanOrEqualTo(Float value) {
            addCriterion("remain_weight >=", value, "remainWeight");
            return (Criteria) this;
        }

        public Criteria andRemainWeightLessThan(Float value) {
            addCriterion("remain_weight <", value, "remainWeight");
            return (Criteria) this;
        }

        public Criteria andRemainWeightLessThanOrEqualTo(Float value) {
            addCriterion("remain_weight <=", value, "remainWeight");
            return (Criteria) this;
        }

        public Criteria andRemainWeightIn(List<Float> values) {
            addCriterion("remain_weight in", values, "remainWeight");
            return (Criteria) this;
        }

        public Criteria andRemainWeightNotIn(List<Float> values) {
            addCriterion("remain_weight not in", values, "remainWeight");
            return (Criteria) this;
        }

        public Criteria andRemainWeightBetween(Float value1, Float value2) {
            addCriterion("remain_weight between", value1, value2, "remainWeight");
            return (Criteria) this;
        }

        public Criteria andRemainWeightNotBetween(Float value1, Float value2) {
            addCriterion("remain_weight not between", value1, value2, "remainWeight");
            return (Criteria) this;
        }

        public Criteria andCategoriesIsNull() {
            addCriterion("categories is null");
            return (Criteria) this;
        }

        public Criteria andCategoriesIsNotNull() {
            addCriterion("categories is not null");
            return (Criteria) this;
        }

        public Criteria andCategoriesEqualTo(Float value) {
            addCriterion("categories =", value, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesNotEqualTo(Float value) {
            addCriterion("categories <>", value, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesGreaterThan(Float value) {
            addCriterion("categories >", value, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesGreaterThanOrEqualTo(Float value) {
            addCriterion("categories >=", value, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesLessThan(Float value) {
            addCriterion("categories <", value, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesLessThanOrEqualTo(Float value) {
            addCriterion("categories <=", value, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesIn(List<Float> values) {
            addCriterion("categories in", values, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesNotIn(List<Float> values) {
            addCriterion("categories not in", values, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesBetween(Float value1, Float value2) {
            addCriterion("categories between", value1, value2, "categories");
            return (Criteria) this;
        }

        public Criteria andCategoriesNotBetween(Float value1, Float value2) {
            addCriterion("categories not between", value1, value2, "categories");
            return (Criteria) this;
        }

        public Criteria andRpStoretimeIsNull() {
            addCriterion("rp_storetime is null");
            return (Criteria) this;
        }

        public Criteria andRpStoretimeIsNotNull() {
            addCriterion("rp_storetime is not null");
            return (Criteria) this;
        }

        public Criteria andRpStoretimeEqualTo(Float value) {
            addCriterion("rp_storetime =", value, "rpStoretime");
            return (Criteria) this;
        }

        public Criteria andRpStoretimeNotEqualTo(Float value) {
            addCriterion("rp_storetime <>", value, "rpStoretime");
            return (Criteria) this;
        }

        public Criteria andRpStoretimeGreaterThan(Float value) {
            addCriterion("rp_storetime >", value, "rpStoretime");
            return (Criteria) this;
        }

        public Criteria andRpStoretimeGreaterThanOrEqualTo(Float value) {
            addCriterion("rp_storetime >=", value, "rpStoretime");
            return (Criteria) this;
        }

        public Criteria andRpStoretimeLessThan(Float value) {
            addCriterion("rp_storetime <", value, "rpStoretime");
            return (Criteria) this;
        }

        public Criteria andRpStoretimeLessThanOrEqualTo(Float value) {
            addCriterion("rp_storetime <=", value, "rpStoretime");
            return (Criteria) this;
        }

        public Criteria andRpStoretimeIn(List<Float> values) {
            addCriterion("rp_storetime in", values, "rpStoretime");
            return (Criteria) this;
        }

        public Criteria andRpStoretimeNotIn(List<Float> values) {
            addCriterion("rp_storetime not in", values, "rpStoretime");
            return (Criteria) this;
        }

        public Criteria andRpStoretimeBetween(Float value1, Float value2) {
            addCriterion("rp_storetime between", value1, value2, "rpStoretime");
            return (Criteria) this;
        }

        public Criteria andRpStoretimeNotBetween(Float value1, Float value2) {
            addCriterion("rp_storetime not between", value1, value2, "rpStoretime");
            return (Criteria) this;
        }

        public Criteria andPvStoretimeIsNull() {
            addCriterion("pv_storetime is null");
            return (Criteria) this;
        }

        public Criteria andPvStoretimeIsNotNull() {
            addCriterion("pv_storetime is not null");
            return (Criteria) this;
        }

        public Criteria andPvStoretimeEqualTo(Float value) {
            addCriterion("pv_storetime =", value, "pvStoretime");
            return (Criteria) this;
        }

        public Criteria andPvStoretimeNotEqualTo(Float value) {
            addCriterion("pv_storetime <>", value, "pvStoretime");
            return (Criteria) this;
        }

        public Criteria andPvStoretimeGreaterThan(Float value) {
            addCriterion("pv_storetime >", value, "pvStoretime");
            return (Criteria) this;
        }

        public Criteria andPvStoretimeGreaterThanOrEqualTo(Float value) {
            addCriterion("pv_storetime >=", value, "pvStoretime");
            return (Criteria) this;
        }

        public Criteria andPvStoretimeLessThan(Float value) {
            addCriterion("pv_storetime <", value, "pvStoretime");
            return (Criteria) this;
        }

        public Criteria andPvStoretimeLessThanOrEqualTo(Float value) {
            addCriterion("pv_storetime <=", value, "pvStoretime");
            return (Criteria) this;
        }

        public Criteria andPvStoretimeIn(List<Float> values) {
            addCriterion("pv_storetime in", values, "pvStoretime");
            return (Criteria) this;
        }

        public Criteria andPvStoretimeNotIn(List<Float> values) {
            addCriterion("pv_storetime not in", values, "pvStoretime");
            return (Criteria) this;
        }

        public Criteria andPvStoretimeBetween(Float value1, Float value2) {
            addCriterion("pv_storetime between", value1, value2, "pvStoretime");
            return (Criteria) this;
        }

        public Criteria andPvStoretimeNotBetween(Float value1, Float value2) {
            addCriterion("pv_storetime not between", value1, value2, "pvStoretime");
            return (Criteria) this;
        }

        public Criteria andInspectionIsNull() {
            addCriterion("inspection is null");
            return (Criteria) this;
        }

        public Criteria andInspectionIsNotNull() {
            addCriterion("inspection is not null");
            return (Criteria) this;
        }

        public Criteria andInspectionEqualTo(Integer value) {
            addCriterion("inspection =", value, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionNotEqualTo(Integer value) {
            addCriterion("inspection <>", value, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionGreaterThan(Integer value) {
            addCriterion("inspection >", value, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionGreaterThanOrEqualTo(Integer value) {
            addCriterion("inspection >=", value, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionLessThan(Integer value) {
            addCriterion("inspection <", value, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionLessThanOrEqualTo(Integer value) {
            addCriterion("inspection <=", value, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionIn(List<Integer> values) {
            addCriterion("inspection in", values, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionNotIn(List<Integer> values) {
            addCriterion("inspection not in", values, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionBetween(Integer value1, Integer value2) {
            addCriterion("inspection between", value1, value2, "inspection");
            return (Criteria) this;
        }

        public Criteria andInspectionNotBetween(Integer value1, Integer value2) {
            addCriterion("inspection not between", value1, value2, "inspection");
            return (Criteria) this;
        }

        public Criteria andTobStatusIsNull() {
            addCriterion("tob_status is null");
            return (Criteria) this;
        }

        public Criteria andTobStatusIsNotNull() {
            addCriterion("tob_status is not null");
            return (Criteria) this;
        }

        public Criteria andTobStatusEqualTo(Integer value) {
            addCriterion("tob_status =", value, "tobStatus");
            return (Criteria) this;
        }

        public Criteria andTobStatusNotEqualTo(Integer value) {
            addCriterion("tob_status <>", value, "tobStatus");
            return (Criteria) this;
        }

        public Criteria andTobStatusGreaterThan(Integer value) {
            addCriterion("tob_status >", value, "tobStatus");
            return (Criteria) this;
        }

        public Criteria andTobStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("tob_status >=", value, "tobStatus");
            return (Criteria) this;
        }

        public Criteria andTobStatusLessThan(Integer value) {
            addCriterion("tob_status <", value, "tobStatus");
            return (Criteria) this;
        }

        public Criteria andTobStatusLessThanOrEqualTo(Integer value) {
            addCriterion("tob_status <=", value, "tobStatus");
            return (Criteria) this;
        }

        public Criteria andTobStatusIn(List<Integer> values) {
            addCriterion("tob_status in", values, "tobStatus");
            return (Criteria) this;
        }

        public Criteria andTobStatusNotIn(List<Integer> values) {
            addCriterion("tob_status not in", values, "tobStatus");
            return (Criteria) this;
        }

        public Criteria andTobStatusBetween(Integer value1, Integer value2) {
            addCriterion("tob_status between", value1, value2, "tobStatus");
            return (Criteria) this;
        }

        public Criteria andTobStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("tob_status not between", value1, value2, "tobStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusIsNull() {
            addCriterion("process_status is null");
            return (Criteria) this;
        }

        public Criteria andProcessStatusIsNotNull() {
            addCriterion("process_status is not null");
            return (Criteria) this;
        }

        public Criteria andProcessStatusEqualTo(Integer value) {
            addCriterion("process_status =", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusNotEqualTo(Integer value) {
            addCriterion("process_status <>", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusGreaterThan(Integer value) {
            addCriterion("process_status >", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("process_status >=", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusLessThan(Integer value) {
            addCriterion("process_status <", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusLessThanOrEqualTo(Integer value) {
            addCriterion("process_status <=", value, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusIn(List<Integer> values) {
            addCriterion("process_status in", values, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusNotIn(List<Integer> values) {
            addCriterion("process_status not in", values, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusBetween(Integer value1, Integer value2) {
            addCriterion("process_status between", value1, value2, "processStatus");
            return (Criteria) this;
        }

        public Criteria andProcessStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("process_status not between", value1, value2, "processStatus");
            return (Criteria) this;
        }

        public Criteria andInOutStatusIsNull() {
            addCriterion("in_out_status is null");
            return (Criteria) this;
        }

        public Criteria andInOutStatusIsNotNull() {
            addCriterion("in_out_status is not null");
            return (Criteria) this;
        }

        public Criteria andInOutStatusEqualTo(Integer value) {
            addCriterion("in_out_status =", value, "inOutStatus");
            return (Criteria) this;
        }

        public Criteria andInOutStatusNotEqualTo(Integer value) {
            addCriterion("in_out_status <>", value, "inOutStatus");
            return (Criteria) this;
        }

        public Criteria andInOutStatusGreaterThan(Integer value) {
            addCriterion("in_out_status >", value, "inOutStatus");
            return (Criteria) this;
        }

        public Criteria andInOutStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("in_out_status >=", value, "inOutStatus");
            return (Criteria) this;
        }

        public Criteria andInOutStatusLessThan(Integer value) {
            addCriterion("in_out_status <", value, "inOutStatus");
            return (Criteria) this;
        }

        public Criteria andInOutStatusLessThanOrEqualTo(Integer value) {
            addCriterion("in_out_status <=", value, "inOutStatus");
            return (Criteria) this;
        }

        public Criteria andInOutStatusIn(List<Integer> values) {
            addCriterion("in_out_status in", values, "inOutStatus");
            return (Criteria) this;
        }

        public Criteria andInOutStatusNotIn(List<Integer> values) {
            addCriterion("in_out_status not in", values, "inOutStatus");
            return (Criteria) this;
        }

        public Criteria andInOutStatusBetween(Integer value1, Integer value2) {
            addCriterion("in_out_status between", value1, value2, "inOutStatus");
            return (Criteria) this;
        }

        public Criteria andInOutStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("in_out_status not between", value1, value2, "inOutStatus");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeDayIsNull() {
            addCriterion("residence_time_day is null");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeDayIsNotNull() {
            addCriterion("residence_time_day is not null");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeDayEqualTo(Integer value) {
            addCriterion("residence_time_day =", value, "residenceTimeDay");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeDayNotEqualTo(Integer value) {
            addCriterion("residence_time_day <>", value, "residenceTimeDay");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeDayGreaterThan(Integer value) {
            addCriterion("residence_time_day >", value, "residenceTimeDay");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeDayGreaterThanOrEqualTo(Integer value) {
            addCriterion("residence_time_day >=", value, "residenceTimeDay");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeDayLessThan(Integer value) {
            addCriterion("residence_time_day <", value, "residenceTimeDay");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeDayLessThanOrEqualTo(Integer value) {
            addCriterion("residence_time_day <=", value, "residenceTimeDay");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeDayIn(List<Integer> values) {
            addCriterion("residence_time_day in", values, "residenceTimeDay");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeDayNotIn(List<Integer> values) {
            addCriterion("residence_time_day not in", values, "residenceTimeDay");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeDayBetween(Integer value1, Integer value2) {
            addCriterion("residence_time_day between", value1, value2, "residenceTimeDay");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeDayNotBetween(Integer value1, Integer value2) {
            addCriterion("residence_time_day not between", value1, value2, "residenceTimeDay");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeHourIsNull() {
            addCriterion("residence_time_hour is null");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeHourIsNotNull() {
            addCriterion("residence_time_hour is not null");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeHourEqualTo(Integer value) {
            addCriterion("residence_time_hour =", value, "residenceTimeHour");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeHourNotEqualTo(Integer value) {
            addCriterion("residence_time_hour <>", value, "residenceTimeHour");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeHourGreaterThan(Integer value) {
            addCriterion("residence_time_hour >", value, "residenceTimeHour");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeHourGreaterThanOrEqualTo(Integer value) {
            addCriterion("residence_time_hour >=", value, "residenceTimeHour");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeHourLessThan(Integer value) {
            addCriterion("residence_time_hour <", value, "residenceTimeHour");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeHourLessThanOrEqualTo(Integer value) {
            addCriterion("residence_time_hour <=", value, "residenceTimeHour");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeHourIn(List<Integer> values) {
            addCriterion("residence_time_hour in", values, "residenceTimeHour");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeHourNotIn(List<Integer> values) {
            addCriterion("residence_time_hour not in", values, "residenceTimeHour");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeHourBetween(Integer value1, Integer value2) {
            addCriterion("residence_time_hour between", value1, value2, "residenceTimeHour");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeHourNotBetween(Integer value1, Integer value2) {
            addCriterion("residence_time_hour not between", value1, value2, "residenceTimeHour");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeMinuteIsNull() {
            addCriterion("residence_time_minute is null");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeMinuteIsNotNull() {
            addCriterion("residence_time_minute is not null");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeMinuteEqualTo(Integer value) {
            addCriterion("residence_time_minute =", value, "residenceTimeMinute");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeMinuteNotEqualTo(Integer value) {
            addCriterion("residence_time_minute <>", value, "residenceTimeMinute");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeMinuteGreaterThan(Integer value) {
            addCriterion("residence_time_minute >", value, "residenceTimeMinute");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeMinuteGreaterThanOrEqualTo(Integer value) {
            addCriterion("residence_time_minute >=", value, "residenceTimeMinute");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeMinuteLessThan(Integer value) {
            addCriterion("residence_time_minute <", value, "residenceTimeMinute");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeMinuteLessThanOrEqualTo(Integer value) {
            addCriterion("residence_time_minute <=", value, "residenceTimeMinute");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeMinuteIn(List<Integer> values) {
            addCriterion("residence_time_minute in", values, "residenceTimeMinute");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeMinuteNotIn(List<Integer> values) {
            addCriterion("residence_time_minute not in", values, "residenceTimeMinute");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeMinuteBetween(Integer value1, Integer value2) {
            addCriterion("residence_time_minute between", value1, value2, "residenceTimeMinute");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeMinuteNotBetween(Integer value1, Integer value2) {
            addCriterion("residence_time_minute not between", value1, value2, "residenceTimeMinute");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeSecondsIsNull() {
            addCriterion("residence_time_seconds is null");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeSecondsIsNotNull() {
            addCriterion("residence_time_seconds is not null");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeSecondsEqualTo(Integer value) {
            addCriterion("residence_time_seconds =", value, "residenceTimeSeconds");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeSecondsNotEqualTo(Integer value) {
            addCriterion("residence_time_seconds <>", value, "residenceTimeSeconds");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeSecondsGreaterThan(Integer value) {
            addCriterion("residence_time_seconds >", value, "residenceTimeSeconds");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeSecondsGreaterThanOrEqualTo(Integer value) {
            addCriterion("residence_time_seconds >=", value, "residenceTimeSeconds");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeSecondsLessThan(Integer value) {
            addCriterion("residence_time_seconds <", value, "residenceTimeSeconds");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeSecondsLessThanOrEqualTo(Integer value) {
            addCriterion("residence_time_seconds <=", value, "residenceTimeSeconds");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeSecondsIn(List<Integer> values) {
            addCriterion("residence_time_seconds in", values, "residenceTimeSeconds");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeSecondsNotIn(List<Integer> values) {
            addCriterion("residence_time_seconds not in", values, "residenceTimeSeconds");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeSecondsBetween(Integer value1, Integer value2) {
            addCriterion("residence_time_seconds between", value1, value2, "residenceTimeSeconds");
            return (Criteria) this;
        }

        public Criteria andResidenceTimeSecondsNotBetween(Integer value1, Integer value2) {
            addCriterion("residence_time_seconds not between", value1, value2, "residenceTimeSeconds");
            return (Criteria) this;
        }

        public Criteria andLoadingStartTimeIsNull() {
            addCriterion("loading_start_time is null");
            return (Criteria) this;
        }

        public Criteria andLoadingStartTimeIsNotNull() {
            addCriterion("loading_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andLoadingStartTimeEqualTo(Date value) {
            addCriterion("loading_start_time =", value, "loadingStartTime");
            return (Criteria) this;
        }

        public Criteria andLoadingStartTimeNotEqualTo(Date value) {
            addCriterion("loading_start_time <>", value, "loadingStartTime");
            return (Criteria) this;
        }

        public Criteria andLoadingStartTimeGreaterThan(Date value) {
            addCriterion("loading_start_time >", value, "loadingStartTime");
            return (Criteria) this;
        }

        public Criteria andLoadingStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("loading_start_time >=", value, "loadingStartTime");
            return (Criteria) this;
        }

        public Criteria andLoadingStartTimeLessThan(Date value) {
            addCriterion("loading_start_time <", value, "loadingStartTime");
            return (Criteria) this;
        }

        public Criteria andLoadingStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("loading_start_time <=", value, "loadingStartTime");
            return (Criteria) this;
        }

        public Criteria andLoadingStartTimeIn(List<Date> values) {
            addCriterion("loading_start_time in", values, "loadingStartTime");
            return (Criteria) this;
        }

        public Criteria andLoadingStartTimeNotIn(List<Date> values) {
            addCriterion("loading_start_time not in", values, "loadingStartTime");
            return (Criteria) this;
        }

        public Criteria andLoadingStartTimeBetween(Date value1, Date value2) {
            addCriterion("loading_start_time between", value1, value2, "loadingStartTime");
            return (Criteria) this;
        }

        public Criteria andLoadingStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("loading_start_time not between", value1, value2, "loadingStartTime");
            return (Criteria) this;
        }

        public Criteria andLoadingEndTimeIsNull() {
            addCriterion("loading_end_time is null");
            return (Criteria) this;
        }

        public Criteria andLoadingEndTimeIsNotNull() {
            addCriterion("loading_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andLoadingEndTimeEqualTo(Date value) {
            addCriterion("loading_end_time =", value, "loadingEndTime");
            return (Criteria) this;
        }

        public Criteria andLoadingEndTimeNotEqualTo(Date value) {
            addCriterion("loading_end_time <>", value, "loadingEndTime");
            return (Criteria) this;
        }

        public Criteria andLoadingEndTimeGreaterThan(Date value) {
            addCriterion("loading_end_time >", value, "loadingEndTime");
            return (Criteria) this;
        }

        public Criteria andLoadingEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("loading_end_time >=", value, "loadingEndTime");
            return (Criteria) this;
        }

        public Criteria andLoadingEndTimeLessThan(Date value) {
            addCriterion("loading_end_time <", value, "loadingEndTime");
            return (Criteria) this;
        }

        public Criteria andLoadingEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("loading_end_time <=", value, "loadingEndTime");
            return (Criteria) this;
        }

        public Criteria andLoadingEndTimeIn(List<Date> values) {
            addCriterion("loading_end_time in", values, "loadingEndTime");
            return (Criteria) this;
        }

        public Criteria andLoadingEndTimeNotIn(List<Date> values) {
            addCriterion("loading_end_time not in", values, "loadingEndTime");
            return (Criteria) this;
        }

        public Criteria andLoadingEndTimeBetween(Date value1, Date value2) {
            addCriterion("loading_end_time between", value1, value2, "loadingEndTime");
            return (Criteria) this;
        }

        public Criteria andLoadingEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("loading_end_time not between", value1, value2, "loadingEndTime");
            return (Criteria) this;
        }

        public Criteria andDischargeStartTimeIsNull() {
            addCriterion("discharge_start_time is null");
            return (Criteria) this;
        }

        public Criteria andDischargeStartTimeIsNotNull() {
            addCriterion("discharge_start_time is not null");
            return (Criteria) this;
        }

        public Criteria andDischargeStartTimeEqualTo(Date value) {
            addCriterion("discharge_start_time =", value, "dischargeStartTime");
            return (Criteria) this;
        }

        public Criteria andDischargeStartTimeNotEqualTo(Date value) {
            addCriterion("discharge_start_time <>", value, "dischargeStartTime");
            return (Criteria) this;
        }

        public Criteria andDischargeStartTimeGreaterThan(Date value) {
            addCriterion("discharge_start_time >", value, "dischargeStartTime");
            return (Criteria) this;
        }

        public Criteria andDischargeStartTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("discharge_start_time >=", value, "dischargeStartTime");
            return (Criteria) this;
        }

        public Criteria andDischargeStartTimeLessThan(Date value) {
            addCriterion("discharge_start_time <", value, "dischargeStartTime");
            return (Criteria) this;
        }

        public Criteria andDischargeStartTimeLessThanOrEqualTo(Date value) {
            addCriterion("discharge_start_time <=", value, "dischargeStartTime");
            return (Criteria) this;
        }

        public Criteria andDischargeStartTimeIn(List<Date> values) {
            addCriterion("discharge_start_time in", values, "dischargeStartTime");
            return (Criteria) this;
        }

        public Criteria andDischargeStartTimeNotIn(List<Date> values) {
            addCriterion("discharge_start_time not in", values, "dischargeStartTime");
            return (Criteria) this;
        }

        public Criteria andDischargeStartTimeBetween(Date value1, Date value2) {
            addCriterion("discharge_start_time between", value1, value2, "dischargeStartTime");
            return (Criteria) this;
        }

        public Criteria andDischargeStartTimeNotBetween(Date value1, Date value2) {
            addCriterion("discharge_start_time not between", value1, value2, "dischargeStartTime");
            return (Criteria) this;
        }

        public Criteria andDischargeEndTimeIsNull() {
            addCriterion("discharge_end_time is null");
            return (Criteria) this;
        }

        public Criteria andDischargeEndTimeIsNotNull() {
            addCriterion("discharge_end_time is not null");
            return (Criteria) this;
        }

        public Criteria andDischargeEndTimeEqualTo(Date value) {
            addCriterion("discharge_end_time =", value, "dischargeEndTime");
            return (Criteria) this;
        }

        public Criteria andDischargeEndTimeNotEqualTo(Date value) {
            addCriterion("discharge_end_time <>", value, "dischargeEndTime");
            return (Criteria) this;
        }

        public Criteria andDischargeEndTimeGreaterThan(Date value) {
            addCriterion("discharge_end_time >", value, "dischargeEndTime");
            return (Criteria) this;
        }

        public Criteria andDischargeEndTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("discharge_end_time >=", value, "dischargeEndTime");
            return (Criteria) this;
        }

        public Criteria andDischargeEndTimeLessThan(Date value) {
            addCriterion("discharge_end_time <", value, "dischargeEndTime");
            return (Criteria) this;
        }

        public Criteria andDischargeEndTimeLessThanOrEqualTo(Date value) {
            addCriterion("discharge_end_time <=", value, "dischargeEndTime");
            return (Criteria) this;
        }

        public Criteria andDischargeEndTimeIn(List<Date> values) {
            addCriterion("discharge_end_time in", values, "dischargeEndTime");
            return (Criteria) this;
        }

        public Criteria andDischargeEndTimeNotIn(List<Date> values) {
            addCriterion("discharge_end_time not in", values, "dischargeEndTime");
            return (Criteria) this;
        }

        public Criteria andDischargeEndTimeBetween(Date value1, Date value2) {
            addCriterion("discharge_end_time between", value1, value2, "dischargeEndTime");
            return (Criteria) this;
        }

        public Criteria andDischargeEndTimeNotBetween(Date value1, Date value2) {
            addCriterion("discharge_end_time not between", value1, value2, "dischargeEndTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SILOINFO
     *
     * @mbg.generated do_not_delete_during_merge Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SILOINFO
     *
     * @mbg.generated Sat Dec 02 10:57:53 GMT+08:00 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}