server:
  port: 9090
  ssl:
    key-store: classpath:tomact.keystore
    key-store-password: 123456
    key-store-type: JKS
    key-alias: tomact
    enabled: true
  error:
    whitelabel:
      enabled: false
    include-message: always
    include-binding-errors: never
    include-stacktrace: never
  servlet:
    context-path: /chapter3
  tomcat:
    uri-encoding: utf-8
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/vhr?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
mybook:
  name: 罗贯中
  author: 罗贯中
  price: 300
my:
  users:
    - name: 江南一点雨
      address: China
      favorites:
        - 足球
        - 徒步
        - Coding
    - name: sang
      address: GZ
      favorites:
        - 阅读
        - 吉他