package com.example.mybatis.mapper;

import com.example.mybatis.model.SysConfig;
import com.example.mybatis.model.SysConfigExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface SysConfigMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    long countByExample(SysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    int deleteByExample(SysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    int deleteByPrimaryKey(String variable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    int insert(SysConfig row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    int insertSelective(SysConfig row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    List<SysConfig> selectByExampleWithRowbounds(SysConfigExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    List<SysConfig> selectByExample(SysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    SysConfig selectByPrimaryKey(String variable);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    int updateByExampleSelective(@Param("row") SysConfig row, @Param("example") SysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    int updateByExample(@Param("row") SysConfig row, @Param("example") SysConfigExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    int updateByPrimaryKeySelective(SysConfig row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    int updateByPrimaryKey(SysConfig row);
}