package com.example.mybatis.mapper;

import com.example.mybatis.model.SysPrivilege;
import com.example.mybatis.model.SysPrivilegeExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface SysPrivilegeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    long countByExample(SysPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    int deleteByExample(SysPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    int insert(SysPrivilege row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    int insertSelective(SysPrivilege row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    List<SysPrivilege> selectByExampleWithRowbounds(SysPrivilegeExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    List<SysPrivilege> selectByExample(SysPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    SysPrivilege selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    int updateByExampleSelective(@Param("row") SysPrivilege row, @Param("example") SysPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    int updateByExample(@Param("row") SysPrivilege row, @Param("example") SysPrivilegeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    int updateByPrimaryKeySelective(SysPrivilege row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_privilege
     *
     * @mbg.generated Thu Sep 19 10:37:21 CST 2024
     */
    int updateByPrimaryKey(SysPrivilege row);
}